Repository FederatedAI/FATE, pull requests merged in 2019-07, with the labels that each got.

#274 Feature 0.3 scale fit bugs
  examples/hetero_logistic_regression/conf/test_hetero_lr_workflow.json
  examples/hetero_logistic_regression/run_logistic_regression.sh
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/StandardScale.java
  federatedml/feature/hetero_feature_selection/feature_selection_guest.py
  federatedml/feature/hetero_feature_selection/feature_selection_host.py
  federatedml/feature/min_max_scaler.py
  federatedml/feature/scaler.py
  federatedml/feature/standard_scaler.py
  federatedml/feature/test/min_max_scaler_test.py
  federatedml/feature/test/standard_scaler_test.py
  federatedml/logistic_regression/base_logistic_regression.py
  federatedml/param/param.py
  federatedml/statistic/intersect/README.md
  federatedml/statistic/intersect/images/RSA_intersection.png
  federatedml/statistic/intersect/images/sample.png
  federatedml/statistic/intersect/intersect_guest.py
  federatedml/statistic/intersect/intersect_host.py
  federatedml/util/fate_operator.py
  federatedml/util/param_checker.py
  workflow/hetero_feature_selection_workflow/hetero_feature_selection_guest_workflow.py
  workflow/hetero_feature_selection_workflow/hetero_feature_selection_host_workflow.py
  workflow/workflow.py
Labels: bug

#277 Feature 0.3 scale fit bugs
  arch/api/proto/feature_engineer_result_pb2.py
  arch/task_manager/README.md
  examples/hetero_logistic_regression/conf/test_hetero_lr_workflow.json
  workflow/workflow.py
Labels: bug

#285 Feature 0.3 scale fit bugs
  federatedml/feature/feature_selection.py
  federatedml/feature/min_max_scaler.py
  federatedml/feature/scaler.py
  federatedml/feature/standard_scaler.py
  federatedml/feature/test/min_max_scaler_test.py
  federatedml/feature/test/standard_scaler_test.py
  federatedml/util/param_checker.py
  workflow/conf/param_validation.json
  workflow/workflow.py
Labels: bug

#322 Feature 1.0 evaluation fix bugs
  federatedml/evaluation/evaluation.py
Labels: bug

#324 Improve the fate-flow metric storage
  fate_flow/db/db_models.py
  fate_flow/manager/tracking.py
  fate_flow/settings.py
Labels: enhancement

#326 fate-serving-change
  arch/core/src/main/java/com/webank/ai/fate/core/network/http/client/HttpClientPool.java
  arch/core/src/main/java/com/webank/ai/fate/core/utils/Configuration.java
  arch/core/src/main/java/com/webank/ai/fate/core/utils/ObjectTransform.java
  cluster-deploy/example-dir-tree/serving-server/conf/log4j2.properties
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/EncryptMethod.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/utils/EncryptUtils.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/BaseModel.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/HeteroLR.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/adapter/processing/PassPreProcessing.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/manger/InferenceManager.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/utils/InferenceUtils.java
  fate-serving/serving-server/src/main/resources/log4j2.properties
Labels: configuration, enhancement

#330 fate_flow: fix some bug on cluster mode
  arch/api/model_manager/manager.py
  arch/api/proto/pipeline_pb2.py
  arch/proto/pipeline.proto
  fate_flow/apps/job_apps.py
  fate_flow/driver/job_controller.py
  fate_flow/manager/model_manager.py
  fate_flow/manager/pipeline_manager.py
  fate_flow/manager/tracking.py
  fate_flow/service.sh
  fate_flow/utils/grpc_utils.py
Labels: enhancement

#333 fate-serving/fate-core improvement
  arch/core/src/main/java/com/webank/ai/fate/core/utils/Configuration.java
  arch/core/src/main/java/com/webank/ai/fate/core/utils/ObjectTransform.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/manger/InferenceManager.java
Labels: enhancement

#335 update arch api doct
  doc/api/eggroll_api.md
  doc/api/federation_api.md
Labels: enhancement
