Repository FederatedAI/FATE, pull requests merged in 2019-05, with the labels that each got.

#143 Feature 0.2 fix bug 5 14
  arch/api/utils/upload.py
  arch/task_manager/example_conf/test_hetero_lr_workflow.json
  arch/task_manager/example_conf/test_intersect_workflow.json
  examples/load_file/load_file.py
  federatedml/feature/imputer.py
  federatedml/feature/scaler.py
  federatedml/feature/test/imputer_test.py
  federatedml/feature/test/min_max_scaler_test.py
  federatedml/feature/test/standard_scaler_test.py
  federatedml/param/param.py
  federatedml/statistic/intersect/intersect_host.py
  workflow/workflow.py
Labels: bug

#152 add operator on fixedpoint
  federatedml/secureprotol/fate_paillier.py
  federatedml/secureprotol/fixedpoint.py
  federatedml/secureprotol/test/fate_paillier_test.py
  federatedml/secureprotol/test/fixedpoin_test.py
Labels: enhancement

#133 Add min_test_task
  examples/min_test_task/README.md
  examples/min_test_task/config/download.json
  examples/min_test_task/config/download_id_library.json
  examples/min_test_task/config/hetero_lr.json
  examples/min_test_task/config/import_id_library.json
  examples/min_test_task/config/test_intersect_workflow.json
  examples/min_test_task/config/upload.json
  examples/min_test_task/data/breast_a.csv
  examples/min_test_task/data/breast_b.csv
  examples/min_test_task/data/default_credit_a.csv
  examples/min_test_task/data/default_credit_b.csv
  examples/min_test_task/run.sh
  examples/min_test_task/run_task.py
  federatedml/statistic/intersect/intersect_guest.py
Labels: enhancement

#156 add one_vs_rest
  arch/build_py_proto.sh
  examples/hetero_logistic_regression/conf/arbiter_runtime_conf.json
  examples/hetero_logistic_regression/conf/guest_runtime_conf.json
  examples/hetero_logistic_regression/conf/host_runtime_conf.json
  federatedml/evaluation/evaluation.py
  federatedml/feature/imputer.py
  federatedml/feature/min_max_scaler.py
  federatedml/feature/scaler.py
  federatedml/feature/standard_scaler.py
  federatedml/logistic_regression/base_logistic_regression.py
  federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_arbiter.py
  federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
  federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
  federatedml/one_vs_rest/one_vs_rest.py
  federatedml/optim/federated_aggregator/hetero_federated_aggregator.py
  federatedml/optim/gradient/logistic_gradient.py
  federatedml/param/param.py
  federatedml/secureprotol/__init__.py
  federatedml/secureprotol/encrypt_mode.py
  federatedml/util/fate_operator.py
  workflow/workflow.py
Labels: enhancement

#157 Feature 0.3 secureboost
  arch/api/proto/boosting_tree_model_param_pb2.py
  arch/api/proto/data_io_meta_pb2.py
  arch/api/proto/one_vs_rest_param_pb2.py
  arch/proto/boosting-tree-model-param.proto
  arch/proto/data-io-meta.proto
  arch/proto/one-vs-rest-param.proto
  federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
  federatedml/param/param.py
  federatedml/secureprotol/encrypt_mode.py
  federatedml/secureprotol/test/encrypt_mode_test.py
  federatedml/tree/boosting_tree.py
  federatedml/tree/decision_tree.py
  federatedml/tree/hetero_decision_tree_guest.py
  federatedml/tree/hetero_decision_tree_host.py
  federatedml/tree/hetero_secureboosting_tree_guest.py
  federatedml/tree/hetero_secureboosting_tree_host.py
  federatedml/tree/splitter.py
  federatedml/util/data_io.py
  federatedml/util/param_checker.py
  federatedml/util/test/data_io_test.py
  federatedml/util/test/parameter_checker_test.py
  workflow/conf/param_validation.json
  workflow/hetero_secureboosting_tree_workflow/hetero_secureboosting_tree_host_workflow.py
Labels: enhancement

#166 fix one_vs_rest save_model namespace
  federatedml/one_vs_rest/one_vs_rest.py
Labels: bug

#171 fix one_vs_rest predict label type not match input_data type bug
  federatedml/one_vs_rest/one_vs_rest.py
Labels: bug

#178 fix bug of param-check and feature-selection
  federatedml/feature/feature_selection.py
  federatedml/util/param_checker.py
Labels: bug

#181 Feature 0.3 arch
  arch/api/cluster/eggroll.py
  arch/eggroll/roll/src/main/java/com/webank/ai/fate/eggroll/roll/service/async/callback/PutAllProcessorListenableFutureCallback.java
  arch/pom.xml
Labels: code review
