Repository FederatedAI/FATE, pull requests merged in 2019-08, with the labels that each got.

#359 Feature 1.0 flow
  arch/api/storage.py
  fate_flow/apps/data_access_app.py
  fate_flow/apps/job_apps.py
  fate_flow/apps/table_app.py
  fate_flow/apps/tracking_app.py
  fate_flow/db/db_models.py
  fate_flow/driver/job_controller.py
  fate_flow/driver/job_detector.py
  fate_flow/driver/scheduler.py
  fate_flow/examples/test_hetero_lr_job_conf.json
  fate_flow/examples/upload_guest.json
  fate_flow/examples/upload_host.json
  fate_flow/fate_flow_client.py
  fate_flow/fate_flow_server.py
  fate_flow/manager/tracking.py
  fate_flow/settings.py
  fate_flow/utils/api_utils.py
  fate_flow/utils/grpc_utils.py
  fate_flow/utils/job_utils.py
Labels: code review

#365 Contributor affine cipher
  federatedml/secureprotol/affine.py
  federatedml/secureprotol/affine_encoder.py
  federatedml/secureprotol/encrypt.py
  federatedml/secureprotol/test/affine_test.py
Labels: contributor

#376 Feature 1.0 flow
  fate_flow/apps/job_apps.py
  fate_flow/apps/machine_learning_model_app.py
  fate_flow/apps/tracking_app.py
  fate_flow/db/db_models.py
  fate_flow/driver/dag_scheduler.py
  fate_flow/driver/job_controller.py
  fate_flow/driver/job_detector.py
  fate_flow/driver/task_executor.py
  fate_flow/driver/task_scheduler.py
  fate_flow/entity/runtime_config.py
  fate_flow/entity/service_support_config.py
  fate_flow/examples/download_guest.json
  fate_flow/examples/download_host.json
  fate_flow/examples/download_id_library_guest.json
  fate_flow/examples/download_id_library_host.json
  fate_flow/examples/get_table_info.json
  fate_flow/examples/import_id_library_guest.json
  fate_flow/examples/import_id_library_host.json
  fate_flow/examples/query_model_version.json
  fate_flow/examples/test_dataio_job_conf.json
  fate_flow/examples/test_hetero_feature_binning_job_conf.json
  fate_flow/examples/test_hetero_feature_selection_job_conf.json
  fate_flow/examples/test_hetero_lr_job_all_conf.json
  fate_flow/examples/test_hetero_lr_job_conf.json
  fate_flow/examples/test_homolr_job_conf.json
  fate_flow/examples/test_secureboost_predict_job_conf.json
  fate_flow/examples/upload_file.json
  fate_flow/examples/upload_homo_guest.json
  fate_flow/examples/upload_homo_host.json
  fate_flow/fate_flow_client.py
  fate_flow/fate_flow_server.py
  fate_flow/manager/queue_manager.py
  fate_flow/manager/tracking.py
  fate_flow/settings.py
  fate_flow/storage/fate_storage.py
  fate_flow/tests/check_all_api.py
  fate_flow/utils/api_utils.py
  fate_flow/utils/grpc_utils.py
  fate_flow/utils/job_utils.py
Labels: enhancement

#382 Feature 0.3.2
  arch/core/src/main/java/com/webank/ai/fate/core/bean/ReturnResult.java
  arch/core/src/main/java/com/webank/ai/fate/core/network/grpc/client/GrpcClientPool.java
  arch/core/src/main/java/com/webank/ai/fate/core/storage/dtable/DistributedDTable.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/BaseContext.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/BaseLoggerPrinter.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/Context.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/Dict.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/GrpcConnectionPool.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/GuestInferenceLoggerPrinter.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/HostInferenceLoggerPrinter.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/LoggerPrinter.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/ModelActionType.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/Predictor.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/bean/Request.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/manager/CacheManager.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/monitor/WatchDog.java
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/utils/GetSystemInfo.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/PipelineTask.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/BaseModel.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/HeteroLR.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/HeteroLRGuest.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/HeteroLRHost.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/Imputer.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/MinMaxScale.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/Outlier.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/Scaler.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/StandardScale.java
  fate-serving/pom.xml
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/ServingServer.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/adapter/dataaccess/DTest.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/adapter/processing/PassPostProcessing.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/adapter/processing/PassPreProcessing.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/adapter/processing/PostProcessing.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/adapter/processing/PreProcessing.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/bean/InferenceRequest.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/manger/InferenceManager.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/service/InferenceService.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/service/ModelService.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/service/ProxyService.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/utils/HttpClientPool.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/utils/InferenceUtils.java
  fate-serving/serving-server/src/main/resources/log4j2.properties
  fate-serving/serving-server/src/main/resources/log4j2.xml
  federatedml/util/data_io.py
Labels: enhancement

#389 Feature 1.0 flow improve
  .gitignore
  arch/api/utils/core.py
  arch/api/utils/pickle.py
  fate_flow/apps/data_access_app.py
  fate_flow/apps/machine_learning_model_app.py
  fate_flow/apps/tracking_app.py
  fate_flow/db/db_models.py
  fate_flow/driver/dsl_parser.py
  fate_flow/driver/executor.py
  fate_flow/driver/job_detector.py
  fate_flow/driver/task_executor.py
  fate_flow/driver/task_scheduler.py
  fate_flow/entity/runtime_config.py
  fate_flow/fate_flow_client.py
  fate_flow/fate_flow_server.py
  fate_flow/manager/model_manager.py
  fate_flow/manager/queue_manager.py
  fate_flow/manager/tracking.py
  fate_flow/settings.py
  fate_flow/utils/api_utils.py
  fate_flow/utils/job_utils.py
Labels: bug, enhancement

#408 fate_flow: fix too many SQL variables error on sqlite
  fate_flow/db/db_models.py
  fate_flow/entity/runtime_config.py
  fate_flow/manager/tracking.py
Labels: code review

#409 fate_flow: modify submit job model info format
  fate_flow/driver/job_controller.py
  fate_flow/manager/tracking.py
Labels: code review

#413 delete useless file of federatedml
  federatedml/feature/test/hetero_sampler_test.py
  federatedml/feature/test/min_max_scaler_test.py
  federatedml/feature/test/standard_scaler_test.py
  federatedml/feature/test/test_hetero_sampler_guest.py
  federatedml/feature/test/test_hetero_sampler_guest.py_bak
  federatedml/feature/test/test_hetero_sampler_host.py
  federatedml/tree/test/hetero_secureboost_test.py
  federatedml/tree/test/test_hetero_secure_boost_guest.py
  federatedml/tree/test/test_hetero_secure_boost_host.py
Labels: bug

#431 change js,and fateboard
  fateboard/src/main/java/com/webank/ai/fate/board/controller/JobDetailController.java
  fateboard/src/main/java/com/webank/ai/fate/board/global/GlobalExceptionHandler.java
  fateboard/src/main/java/com/webank/ai/fate/board/log/LogFileService.java
  fateboard/src/main/java/com/webank/ai/fate/board/services/TaskManagerService.java
  fateboard/src/main/java/com/webank/ai/fate/board/ssh/SshService.java
  fateboard/src/main/java/com/webank/ai/fate/board/utils/HttpClientPool.java
  fateboard/src/main/java/com/webank/ai/fate/board/utils/ResponseUtil.java
  fateboard/src/main/java/com/webank/ai/fate/board/websocket/JobWebSocketService.java
  fateboard/src/main/java/com/webank/ai/fate/board/websocket/LogWebSocketSSHService.java
  fateboard/src/main/resources/static/index.html
  fateboard/src/main/resources/static/static/js/app.f59e8dfd.js
  fateboard/src/main/resources/static/static/js/app.ffc833f6.js
  fateboard/src/main/resources/static/static/js/chunk-08de.e03d5880.js
  fateboard/src/main/resources/static/static/js/chunk-1201.0873bd49.js
  fateboard/src/main/resources/static/static/js/chunk-2ac8.2bae5e17.js
  fateboard/src/main/resources/static/static/js/chunk-2ac8.94014236.js
  fateboard/src/main/resources/static/static/js/chunk-6625.af5884fe.js
  fateboard/src/main/resources/static/static/js/chunk-c9ef.26c8fa6c.js
  fateboard/src/main/resources/static/static/js/chunk-c9ef.bc9c28ec.js
  fateboard/src/main/resources/static/static/js/chunk-libs.0067b84a.js
  fateboard/static/src/icons/dashboard_job_complete.png
  fateboard/static/src/icons/dashboard_job_failed.png
  fateboard/static/src/store/modules/app.js
  fateboard/static/src/styles/dashboard.scss
  fateboard/static/src/styles/running.scss
  fateboard/static/src/utils/chart-options/doubleBar.js
  fateboard/static/src/utils/chart-options/evaluation-curve.js
  fateboard/static/src/utils/chart-options/gauge.js
  fateboard/static/src/utils/index.js
  fateboard/static/src/utils/request.js
  fateboard/static/src/utils/vendor/graphChartHandler.js
  fateboard/static/src/utils/vendor/metricOutputHandler.js
  fateboard/static/src/utils/vendor/modelOutputHandler.js
  fateboard/static/src/views/job-dashboard/index.vue
  fateboard/static/src/views/job-details/CurveLegend.vue
  fateboard/static/src/views/job-details/ModelOutput.vue
  fateboard/static/src/views/job-details/index.vue
  fateboard/static/src/views/job-running/index.vue
  fateboard/static/src/views/layout/components/Navbar.vue
  fateboard/static/src/views/layout/components/SSHConfig.vue
Labels: enhancement

#447 Feature 1.0 flow
  arch/api/proto/default_empty_fill_pb2.py
  arch/build_py_proto.sh
  arch/proto/default-empty-fill.proto
  fate_flow/apps/tracking_app.py
  fate_flow/fate_flow_cli.md
  fate_flow/fate_flow_client.py
  fate_flow/manager/model_manager.py
  fate_flow/utils/detect_utils.py
  fate_flow/utils/job_utils.py
Labels: code review

#449 Feature 1.0 algorithm doc update and examples update
  examples/federatedml-1.0-examples/PREDICT_TASK_README.md
  examples/federatedml-1.0-examples/README.md
  examples/federatedml-1.0-examples/hetero_feature_binning/test_hetero_binning_job_conf.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/test_hetero_lr_cv_job_conf.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/test_hetero_lr_cv_job_dsl.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/test_hetero_lr_job_conf.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/test_hetero_lr_job_conf_one_vs_rest.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/test_hetero_lr_job_dsl_one_vs_rest.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/test_hetero_lr_predict_job_dsl.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/test_hetero_lr_train_job_conf.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/test_hetero_lr_train_job_dsl.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/test_hetero_lr_validate_job_conf.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/test_hetero_lr_validate_job_dsl.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/upload_data_guest_one_vs_rest.json
  examples/federatedml-1.0-examples/hetero_logistic_regression/upload_data_host_one_vs_rest.json
  examples/federatedml-1.0-examples/hetero_secureboost/README.md
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_cross_validation_binary_conf.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_cross_validation_dsl.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_cross_validation_multi_conf.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_cross_validation_regression_conf.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_cv_dsl.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_predict_job_conf.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_train_binary_conf.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_train_dsl.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_train_job_conf.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_train_job_dsl.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_train_multi_conf.json
  examples/federatedml-1.0-examples/hetero_secureboost/test_secureboost_train_regression_conf.json
  examples/federatedml-1.0-examples/homo_logistic_regression/test_homolr_cv_job_conf.json
  examples/federatedml-1.0-examples/homo_logistic_regression/test_homolr_evaluate_job_conf.json
  examples/federatedml-1.0-examples/homo_logistic_regression/test_homolr_evaluate_job_dsl.json
  examples/federatedml-1.0-examples/homo_logistic_regression/test_homolr_predict_job_conf.json
  examples/federatedml-1.0-examples/homo_logistic_regression/test_homolr_train_job_conf.json
  examples/federatedml-1.0-examples/homo_logistic_regression/test_homolr_train_job_dsl.json
  examples/federatedml-1.0-examples/multi_model_pipeline/test_all_conf.json
  examples/federatedml-1.0-examples/multi_model_pipeline/test_all_dsl.json
  examples/federatedml-1.0-examples/quick_run.py
  examples/federatedml-1.0-examples/upload_data_guest.json
  examples/federatedml-1.0-examples/upload_data_host.json
  examples/min_test_task/README.md
  examples/min_test_task/run.sh
  examples/min_test_task/run_task.py
  examples/toy_example/README.md
  federatedml/conf/default_runtime_conf/boosting_tree_param.json
  federatedml/evaluation/evaluation.py
  federatedml/feature/feature_scale/min_max_scale.py
  federatedml/feature/hetero_feature_binning/base_feature_binning.py
  federatedml/feature/one_hot_encoder.py
  federatedml/feature/scale.py
  federatedml/param/boosting_tree_param.py
  federatedml/statistic/data_overview.py
  federatedml/tree/boosting_tree.py
  federatedml/tree/hetero_secureboosting_tree_guest.py
  federatedml/tree/hetero_secureboosting_tree_host.py
Labels: code review

#452 fate_flow: download output data using a comma as a separator
  fate_flow/apps/tracking_app.py
Labels: code review

#455 Feature 1.0 flow
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/utils/ProtobufUtils.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/BaseModel.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/DataIO.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/FeatureSelection.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/HeteroLR.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/Scale.java
  fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/Scaler.java
  fate_flow/fate_flow_cli.md
  fate_flow/fate_flow_client.py
  fate_flow/manager/model_manager.py
  requirements.txt
Labels: code review

#461 Feature 1.0 flow
  fate_flow/db/db_models.py
  fate_flow/driver/task_executor.py
  fate_flow/fate_flow_cli.md
  fate_flow/fate_flow_client.py
  fate_flow/utils/job_utils.py
Labels: code review

#466 change readme
  standalone-deploy/Manual/README.md
Labels: enhancement

#473 Feature 1.0 flow
  fate_flow/README.md
  fate_flow/db/db_models.py
  fate_flow/doc/fate_flow_cli.md
  fate_flow/doc/fate_flow_rest_api.md
  fate_flow/images/fate_flow_arch.png
  fate_flow/images/fate_flow_component_dsl.png
  fate_flow/images/fate_flow_dag.png
  fate_flow/images/fate_flow_dsl.png
  fate_flow/images/federated_learning_pipeline.png
Labels: code review

#481 fate-serving: improve fate-serving readme
  fate-serving/README.md
  fate-serving/images/fate_serving_arch.png
  fate-serving/images/fate_serving_online_pipeline.png
  fate_flow/doc/fate_flow_rest_api.md
Labels: code review

#488 Feature 1.0 change deploy readme
  standalone-deploy/README.md
Labels: document

#508 fix bugs of secureboost' s multi host scene
  README.md
  federatedml/feature/sampler.py
  federatedml/logistic_regression/test/__init__.py
  federatedml/logistic_regression/test/hetero_lr_arbiter_test.py
  federatedml/logistic_regression/test/hetero_lr_guest_test.py
  federatedml/logistic_regression/test/hetero_lr_host_test.py
  federatedml/logistic_regression/test/homo_lr_arbiter.py
  federatedml/logistic_regression/test/homo_lr_guest.py
  federatedml/logistic_regression/test/homo_lr_host.py
  federatedml/logistic_regression/test/homo_lr_test.py
  federatedml/logistic_regression/test/job_id.py
  federatedml/logistic_regression/test/kill.sh
  federatedml/logistic_regression/test/logistic_regression_test.py
  federatedml/logistic_regression/test/start_test.sh
  federatedml/model_selection/KFold.py
  federatedml/tree/hetero_decision_tree_guest.py
  federatedml/tree/hetero_decision_tree_host.py
  federatedml/tree/hetero_secureboosting_tree_guest.py
  federatedml/tree/hetero_secureboosting_tree_host.py
Labels: bug
