Repository FederatedAI/FATE, pull requests merged in 2019-10, with the labels that each got.

#636 Feature 1.0.1 raw intersect reform
  federatedml/evaluation/evaluation.py
  federatedml/statistic/intersect/intersect.py
  federatedml/statistic/intersect/intersect_model.py
Labels: bug

#647 fix bugs both validation and train data need validate during training process
  federatedml/util/validation_strategy.py
Labels: bug

#653 Feature 1.1 fate flow
  arch/api/utils/log_utils.py
  fate_flow/apps/data_access_app.py
  fate_flow/apps/job_app.py
  fate_flow/apps/machine_learning_model_app.py
  fate_flow/apps/permission_app.py
  fate_flow/apps/schedule_app.py
  fate_flow/driver/dag_scheduler.py
  fate_flow/driver/dsl_parser.py
  fate_flow/driver/job_controller.py
  fate_flow/driver/job_detector.py
  fate_flow/driver/task_executor.py
  fate_flow/driver/task_scheduler.py
  fate_flow/entity/constant_config.py
  fate_flow/examples/inference_request.py
  fate_flow/examples/test_hetero_lr_job_conf.json
  fate_flow/fate_flow_client.py
  fate_flow/fate_flow_server.py
  fate_flow/manager/queue_manager.py
  fate_flow/manager/tracking.py
  fate_flow/param/upload_param.py
  fate_flow/settings.py
  fate_flow/tests/check_fate_python_requirement.py
  fate_flow/tests/python3_7_modules.csv
  fate_flow/utils/api_utils.py
  fate_flow/utils/authentication_utils.py
  fate_flow/utils/download.py
  fate_flow/utils/grpc_utils.py
  fate_flow/utils/job_utils.py
  fate_flow/utils/upload.py
  federatedml/conf/default_runtime_conf/download_param.json
  federatedml/conf/default_runtime_conf/upload_param.json
Labels: bug, enhancement

#657 Fix flow bug
  fate_flow/apps/schedule_app.py
  fate_flow/driver/job_detector.py
  fate_flow/driver/task_scheduler.py
  fate_flow/manager/tracking.py
  fate_flow/utils/authentication_utils.py
Labels: bug

#675 fix bugs
  fate_flow/driver/job_controller.py
  fate_flow/driver/task_executor.py
  fate_flow/driver/task_scheduler.py
Labels: bug

#688 fix fate flow bugs
  arch/api/utils/log_utils.py
  fate_flow/apps/data_access_app.py
  fate_flow/apps/tracking_app.py
  fate_flow/driver/task_executor.py
  fate_flow/utils/authentication_utils.py
  fate_flow/utils/download.py
  fate_flow/utils/upload.py
Labels: bug

#708 Feature 1.1 new third round
  federatedml/evaluation/evaluation.py
  federatedml/feature/hetero_feature_binning/base_feature_binning.py
  federatedml/feature/hetero_feature_selection/base_feature_selection.py
  federatedml/param/boosting_tree_param.py
  federatedml/param/encrypted_mode_calculation_param.py
  federatedml/param/linear_regression_param.py
  federatedml/param/poisson_regression_param.py
Labels: bug

#741 Feature 1.1 deploy
  cluster-deploy/scripts/allinone_cluster_configurations.sh
  cluster-deploy/scripts/deploy/eggroll/egg/configurations.sh
  cluster-deploy/scripts/deploy/eggroll/egg/deploy.sh
  cluster-deploy/scripts/deploy/fate_base/mysql/configurations.sh
  cluster-deploy/scripts/deploy/fate_base/mysql/deploy.sh
  cluster-deploy/scripts/deploy_cluster_allinone.sh
  cluster-deploy/scripts/deploy_cluster_multinode.sh
  cluster-deploy/scripts/packaging.sh
Labels: code review

#743 update document
  standalone-deploy/README.md
Labels: document
