Repository FederatedAI/FATE, pull requests merged in 2019-12, with the labels that each got.

#817 Feature 1.2 sklearn
  examples/federatedml-1.x-examples/local_baseline/test_local_baseline_homo_job_conf.json
  examples/federatedml-1.x-examples/local_baseline/test_local_baseline_homo_job_dsl.json
  examples/federatedml-1.x-examples/local_baseline/test_local_baseline_job_conf.json
  examples/federatedml-1.x-examples/local_baseline/test_local_baseline_job_dsl.json
  federatedml/conf/default_runtime_conf/local_baseline_param.json
  federatedml/conf/setting_conf/LocalBaseline.json
  federatedml/linear_model/poisson_regression/base_poisson_regression.py
  federatedml/local_baseline/README.md
  federatedml/local_baseline/__init__.py
  federatedml/local_baseline/local_baseline.py
  federatedml/param/local_baseline_param.py
Labels: enhancement

#838 fix dataio reading tag inputformat bugs
  federatedml/util/data_io.py
Labels: bug

#831 Feature 1.2 spdz
  examples/federatedml-1.x-examples/hetero_pearson/test_conf.json
  examples/federatedml-1.x-examples/hetero_pearson/test_dsl.json
  federatedml/conf/default_runtime_conf/pearson_param.json
  federatedml/conf/setting_conf/HeteroPearson.json
  federatedml/param/pearson_param.py
  federatedml/protobuf/generated/pearson_model_meta_pb2.py
  federatedml/protobuf/generated/pearson_model_param_pb2.py
  federatedml/protobuf/proto/pearson-model-meta.proto
  federatedml/protobuf/proto/pearson-model-param.proto
  federatedml/secureprotol/fate_paillier.py
  federatedml/secureprotol/spdz/__init__.py
  federatedml/secureprotol/spdz/beaver_triples/__init__.py
  federatedml/secureprotol/spdz/beaver_triples/he.py
  federatedml/secureprotol/spdz/communicator/__init__.py
  federatedml/secureprotol/spdz/communicator/federation.py
  federatedml/secureprotol/spdz/quick_demo.py
  federatedml/secureprotol/spdz/spdz.py
  federatedml/secureprotol/spdz/tensor/__init__.py
  federatedml/secureprotol/spdz/tensor/base.py
  federatedml/secureprotol/spdz/tensor/numpy_fix_point.py
  federatedml/secureprotol/spdz/tensor/table_fix_point.py
  federatedml/secureprotol/spdz/utils/__init__.py
  federatedml/secureprotol/spdz/utils/naming.py
  federatedml/secureprotol/spdz/utils/random_utils.py
  federatedml/statistic/correlation/__init__.py
  federatedml/statistic/correlation/pearson.py
  federatedml/transfer_variable/base_transfer_variable.py
  federatedml/transfer_variable/definition/secret_share.json
  federatedml/transfer_variable/definition/transfer_conf.json
  federatedml/transfer_variable/transfer_class/secret_share_transfer_variable.py
Labels: federatedml

#848 fix code errors
  federatedml/secureprotol/README.md
Labels: document

#851 Enhance federation clean
  arch/api/transfer/__init__.py
  arch/api/transfer/cluster.py
  arch/api/transfer/standalone.py
  federatedml/transfer_variable/base_transfer_variable.py
Labels: enhancement

#855 Feature 1.2 hetero nn dev base develop1.2
  federatedml/conf/default_runtime_conf/hetero_nn_param.json
  federatedml/conf/setting_conf/HeteroNN.json
  federatedml/nn/hetero_nn/__init__.py
  federatedml/nn/hetero_nn/backend/__init__.py
  federatedml/nn/hetero_nn/backend/model_builder.py
  federatedml/nn/hetero_nn/backend/ops.py
  federatedml/nn/hetero_nn/backend/tf_keras/__init__.py
  federatedml/nn/hetero_nn/backend/tf_keras/data_generator.py
  federatedml/nn/hetero_nn/backend/tf_keras/hetero_nn_model.py
  federatedml/nn/hetero_nn/backend/tf_keras/interactive/__init__.py
  federatedml/nn/hetero_nn/backend/tf_keras/interactive/dense_model.py
  federatedml/nn/hetero_nn/backend/tf_keras/losses.py
  federatedml/nn/hetero_nn/hetero_nn_base.py
  federatedml/nn/hetero_nn/hetero_nn_guest.py
  federatedml/nn/hetero_nn/hetero_nn_host.py
  federatedml/nn/hetero_nn/hetero_nn_model.py
  federatedml/nn/hetero_nn/model/__init__.py
  federatedml/nn/hetero_nn/model/hetero_nn_bottom_model.py
  federatedml/nn/hetero_nn/model/hetero_nn_top_model.py
  federatedml/nn/hetero_nn/model/interactive_layer.py
  federatedml/nn/hetero_nn/util/__init__.py
  federatedml/nn/hetero_nn/util/random_number_generator.py
  federatedml/nn/homo_nn/backend/tf_keras/nn_model.py
  federatedml/nn/homo_nn/zoo/nn.py
  federatedml/param/hetero_nn_param.py
  federatedml/protobuf/generated/hetero_nn_model_meta_pb2.py
  federatedml/protobuf/generated/hetero_nn_model_param_pb2.py
  federatedml/protobuf/proto/hetero-nn-model-meta.proto
  federatedml/protobuf/proto/hetero-nn-model-param.proto
  federatedml/secureprotol/encrypt.py
  federatedml/transfer_variable/definition/hetero_nn.json
  federatedml/transfer_variable/definition/transfer_conf.json
  federatedml/transfer_variable/transfer_class/hetero_nn_transfer_variable.py
  requirements.txt
Labels: enhancement, federatedml

#871 Develop 1.1.2
  arch/api/proto/model_service_pb2.py
  arch/api/proto/model_service_pb2_grpc.py
  arch/proto/model_service.proto
  fate_flow/apps/machine_learning_model_app.py
  fate_flow/driver/job_controller.py
  fate_flow/driver/task_executor.py
  fate_flow/driver/task_scheduler.py
  fate_flow/examples/bind_model_service.json
  fate_flow/examples/inference_request.py
  fate_flow/fate_flow_client.py
  fate_flow/utils/job_utils.py
  fate_flow/utils/publish_model.py
  federatedml/util/data_io.py
Labels: bug, code review, enhancement

#898 Feature 1.2 hetero nn dev base develop1.2
  examples/federatedml-1.x-examples/hetero_nn/test_build_from_keras.py
  examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_dsl.json
  examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_keras.json
  examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_keras_temperate.json
  federatedml/README.md
  federatedml/nn/hetero_nn/README.md
Labels: document, federatedml
