Repository FederatedAI/FATE, pull requests merged in 2019-09, with the labels that each got.

#521 Develop 1.0.2 sqlitdeploy
  cluster-deploy/example-dir-tree/fateboard/conf/application.properties
  cluster-deploy/scripts/auto-deploy.sh
  fateboard/README.md
  fateboard/pom.xml
  fateboard/src/main/java/com/webank/ai/fate/board/controller/JobDetailController.java
  fateboard/src/main/java/com/webank/ai/fate/board/controller/JobManagerController.java
  fateboard/src/main/java/com/webank/ai/fate/board/utils/HttpClientPool.java
  fateboard/src/main/resources/application.properties
  standalone-deploy/README.md
  standalone-deploy/build_standalone_docker.sh
  standalone-deploy/docker/docker-compose-build.yml
  standalone-deploy/docker/fateboard/docker-entrypoint.sh
  standalone-deploy/docker/mysql/Dockerfile
  standalone-deploy/docker/mysql/init_database.sql
  standalone-deploy/docker/python/Dockerfile
Labels: enhancement

#559 fix feature bug
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/manger/InferenceManager.java
Labels: bug

#568 fix bug of logs
  fateboard/src/main/java/com/webank/ai/fate/board/log/LogFileService.java
  fateboard/src/main/java/com/webank/ai/fate/board/services/LogSshLoadService.java
Labels: bug

#570 Feature 1.0.2 support standalone job on cluster
  arch/api/utils/log_utils.py
  fate_flow/apps/data_access_app.py
  fate_flow/apps/job_app.py
  fate_flow/apps/tracking_app.py
  fate_flow/driver/task_scheduler.py
  fate_flow/fate_flow_client.py
  fate_flow/fate_flow_server.py
  fate_flow/service.sh
  fate_flow/settings.py
Labels: code review

#572 fix evaluation bug for some dsl
  federatedml/evaluation/evaluation.py
Labels: bug

#599 add 1.0.2 release note
  RELEASE.md
Labels: document

#600 update 1.0.2 release note
  RELEASE.md
Labels: code review, document

#627 fix eggroll init error
  doc/api/eggroll_api.md
Labels: bug
