Repository FederatedAI/FATE, pull requests merged in 2019-06, with the labels that each got.

#199 fix one-hot bugs
  federatedml/feature/one_hot_encoder.py
Labels: bug

#200 Feature 0.3 serving
  cluster-deploy/example-dir-tree/serving-server/conf/log4j2.properties
  cluster-deploy/example-dir-tree/serving-server/conf/serving-server.properties
  fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/manager/CacheManager.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/manger/InferenceManager.java
  fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/utils/InferenceUtils.java
  fate-serving/serving-server/src/main/resources/log4j2.properties
  fate-serving/serving-server/src/main/resources/serving-server.properties
Labels: bug

#201 Feature 1.0 intersection update v1
  examples/intersect/conf/guest_runtime_conf.json
  examples/intersect/conf/host_runtime_conf.json
  federatedml/param/param.py
  federatedml/statistic/intersect/intersect.py
  federatedml/statistic/intersect/intersect_guest.py
  federatedml/statistic/intersect/intersect_host.py
  federatedml/util/param_checker.py
  workflow/workflow.py
Labels: enhancement

#203 Feature 0.3 deploy
  README.md
  build_standalone_docker.sh
  cluster-deploy/README.md
  cluster-deploy/scripts/auto-deploy.sh
  cluster-deploy/scripts/auto-packaging.sh
  cluster-deploy/scripts/configurations.sh
  cluster-deploy/scripts/fate-base/install_redis.sh
  requirements.txt
Labels: bug

#206 fix federation crash bug
  arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/transfer/communication/TransferJobScheduler.java
Labels: bug

#210 Feature 0.3 hetero lr temporary rubbish clear
  examples/hetero_logistic_regression/run_logistic_regression.sh
  examples/hetero_secureboosting_tree/run_secureboosting.sh
  examples/homo_logistic_regression/run_logistic_regression.sh
  federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
  federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
  federatedml/optim/gradient/logistic_gradient.py
  federatedml/secureprotol/encrypt_mode.py
  federatedml/statistic/data_overview.py
  federatedml/util/param_checker.py
Labels: enhancement

#233 add release v0.3
  RELEASE.md
Labels: priority:high

#237 Feature 0.3 examples readme
  README.md
  examples/hetero_feature_binning/README.md
  examples/hetero_feature_binning/conf/guest_runtime_conf.json
  examples/hetero_feature_binning/conf/host_runtime_conf.json
  examples/hetero_feature_binning/conf/load_file_tm_guest.json
  examples/hetero_feature_binning/conf/load_file_tm_host.json
  examples/hetero_feature_binning/conf/test_hetero_feature_binning_workflow.json
  examples/hetero_feature_binning/run_binning.py
  examples/hetero_feature_selection/README.md
  examples/hetero_feature_selection/conf/load_file_tm_guest.json
  examples/hetero_feature_selection/conf/load_file_tm_host.json
  examples/hetero_feature_selection/conf/test_feature_selection_workflow.json
  examples/hetero_feature_selection/load_file_functions.py
  examples/hetero_feature_selection/run_feature_selection_standalone.sh
  examples/hetero_logistic_regression/README.md
  examples/hetero_logistic_regression/conf/load_file_tm_guest.json
  examples/hetero_logistic_regression/conf/load_file_tm_host.json
  examples/hetero_logistic_regression/conf/test_hetero_lr_workflow.json
  examples/hetero_secureboosting_tree/README.md
  examples/hetero_secureboosting_tree/conf/hetero_secureboost_tm_submit_conf.json
  examples/hetero_secureboosting_tree/conf/load_file_tm_guest.json
  examples/hetero_secureboosting_tree/conf/load_file_tm_host.json
  examples/homo_logistic_regression/README.md
  examples/homo_logistic_regression/conf/load_file_tm_guest.json
  examples/homo_logistic_regression/conf/load_file_tm_host.json
  examples/homo_logistic_regression/conf/test_homo_lr_workflow.json
  examples/intersect/README.md
  examples/intersect/conf/get_tm_intersect_output.py
  examples/intersect/conf/load_file_tm_guest.json
  examples/intersect/conf/load_file_tm_host.json
  examples/intersect/conf/test_intersect_workflow.json
  examples/min_test_task/run_task.py
  examples/task_manager_examples/README.md
  examples/task_manager_examples/__init__.py
  examples/task_manager_examples/load_file.json
  examples/task_manager_examples/task_manager_client.py
  examples/toy_example/README.md
  examples/toy_example/conf/toy_example_tm_submit.json
  workflow/conf/setting_conf.json
Labels: enhancement

#249 Feature 0.3 algorithm readme
  federatedml/feature/README.md
  federatedml/logistic_regression/README.md
  federatedml/one_vs_rest/README.md
  federatedml/tree/README.md
  federatedml/util/README.md
Labels: enhancement
