Repository FederatedAI/FATE, pull requests merged in 2020-11, with the labels that each got.

#2259 fix benchmark
  examples/README.rst
  examples/benchmark_quality/hetero_linear_regression/local-linr.py
  examples/benchmark_quality/hetero_lr/breast_config.yaml
  examples/benchmark_quality/hetero_lr/default_credit_config.yaml
  examples/benchmark_quality/hetero_lr/epsilon_5k_config.yaml
  examples/benchmark_quality/hetero_lr/give_credit_config.yaml
  examples/benchmark_quality/hetero_lr/sklearn-lr-binary.py
  examples/benchmark_quality/hetero_lr/sklearn-lr-multi.py
  examples/benchmark_quality/hetero_lr/vechile_config.yaml
  examples/benchmark_quality/hetero_lr/vechile_pipeline_config.yaml
  examples/benchmark_quality/homo_lr/breast_lr_config.yaml
  examples/benchmark_quality/homo_lr/default_credit_lr_config.yaml
  examples/benchmark_quality/homo_lr/epsilon_5k_lr_config.yaml
  examples/benchmark_quality/homo_lr/give_credit_lr_config.yaml
  examples/benchmark_quality/homo_lr/give_credit_pipeline_lr_config.yaml
  examples/benchmark_quality/homo_lr/sklearn-lr-binary.py
  examples/config.yaml
  examples/pipeline/demo/pipeline-quick-demo.py
  python/fate_test/fate_test/scripts/benchmark_cli.py
  python/federatedml/param/logistic_regression_param.py
Labels: examples

#2261 rename pipeline cli
  examples/pipeline/README.rst
  python/fate_client/README.rst
  python/fate_client/pipeline/README.rst
  python/fate_client/pipeline/pipeline_cli.py
  python/fate_client/setup.py
  python/fate_test/README.rst
  python/fate_test/setup.py
Labels: document

#2264 edit example & doc
  examples/pipeline/README.rst
  examples/pipeline/upload/pipeline-upload.py
  python/fate_client/pipeline/utils/tools.py
Labels: document, examples

#2267 Feature 1.5 quick run doc
  examples/pipeline/demo/pipeline-mini-demo.py
  python/fate_client/pipeline/README.rst
  python/fate_client/pipeline/component/README.rst
  python/fate_client/pipeline/demo/pipeline-mini-demo.py
Labels: document, examples

#2268 edit doc
  examples/README.rst
  examples/README_zh.rst
Labels: document

#2270 Feature 1.5 quick run doc
  doc/tutorial/pipeline/pipeline_tutorial_0.ipynb
  examples/dsl/v1/README.rst
Labels: document

#2247 Feature 1.5.0 lts deploy doc
  cluster-deploy/README.md
  cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
  cluster-deploy/doc/Fate-exchange_deployment_guide_zh.md
  cluster-deploy/doc/Fate_cluster_install_guide_ansible.md
  cluster-deploy/doc/Fate_guest_install_guide_ansible.md
Labels: deployment, document

#2275 edit doc
  README.md
  examples/pipeline/README.rst
  python/fate_client/pipeline/README.rst
  python/federatedml/README.rst
  python/federatedml/README_zh.rst
  python/federatedml/param/scorecard_param.py
  python/federatedml/statistic/scorecard/README.rst
Labels: document

#2276 fix get input dataset name in dsl version 2
  python/fate_flow/utils/parameter_util.py
Labels: bug

#2277 fix mnist demo in dsl v2
  examples/dsl/v2/homo_nn/mnist_demo/build_mnist_testsuite.py
Labels: examples

#2279 edit hetero_nn readme
  python/federatedml/nn/hetero_nn/README.rst
  python/federatedml/nn/hetero_nn/images/hetero_nn_backward_propagation.png
Labels: document

#2283 Remove log & fix benchmark
  examples/benchmark_quality/hetero_lr/sklearn-lr-binary.py
  examples/benchmark_quality/hetero_lr/vechile_config.yaml
  examples/benchmark_quality/hetero_lr/vechile_pipeline_config.yaml
  examples/benchmark_quality/homo_lr/sklearn-lr-binary.py
  python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_guest.py
  python/federatedml/optim/initialize.py
  python/federatedml/optim/optimizer.py
Labels: examples

#2294 Feature 1.5 formal fix
  examples/benchmark_quality/hetero_lr/sklearn-lr-multi.py
  examples/benchmark_quality/hetero_lr/vechile_pipeline_config.yaml
  examples/benchmark_quality/homo_lr/homo_lr_sklearn_benchmark.json
Labels: examples

#2296 Develop 1.5
  examples/benchmark_quality/hetero_lr/sklearn-lr-multi.py
  examples/benchmark_quality/hetero_lr/vechile_pipeline_config.yaml
  examples/benchmark_quality/homo_lr/homo_lr_sklearn_benchmark.json
  python/federatedml/test/run_test.sh
Labels: examples

#2297 Develop
  examples/benchmark_quality/hetero_lr/sklearn-lr-multi.py
  examples/benchmark_quality/hetero_lr/vechile_pipeline_config.yaml
  examples/benchmark_quality/homo_lr/homo_lr_sklearn_benchmark.json
  python/federatedml/test/run_test.sh
Labels: examples

#2307 Feature 1.5 edit travis
  .travis.yml
  README.md
Labels: enhancement

#2311 fix doc
  python/fate_arch/abc/_computing.py
Labels: document

#2314 edit dsl file， remove need_deploy
  examples/dsl/v1/hetero_logistic_regression/test_lr_with_feature_engineering_dsl.json
Labels: examples

#2318 fix doc format view in readthedoc
  python/fate_arch/abc/_computing.py
Labels: document

#2315 fix doc error
  doc/dsl_conf_v2_setting_guide.rst
Labels: bug

#2329 edit doc
  doc/develop_guide.rst
Labels: document

#2337 edit min-test
  examples/min_test_task/run_task.py
Labels: examples

#2342 fix md links
  doc/readthedoc/conf.py
Labels: document

#2346 edit doc
  examples/pipeline/README.rst
  examples/pipeline/demo/pipeline-upload.py
Labels: document

#2349 edit doc
  examples/pipeline/README.rst
  examples/pipeline/demo/pipeline-upload.py
  python/fate_client/README.rst
Labels: document

#2340 update column expand
  examples/dsl/v1/column_expand/column_expand_testsuite.json
  examples/dsl/v1/column_expand/test_column_expand_job_conf.json
  examples/dsl/v1/column_expand/test_column_expand_job_dsl.json
  examples/dsl/v1/column_expand/test_predict_conf.json
  examples/dsl/v2/column_expand/README.md
  examples/dsl/v2/column_expand/column_expand_testsuite.json
  examples/dsl/v2/column_expand/test_column_expand_job_conf.json
  examples/dsl/v2/column_expand/test_column_expand_job_dsl.json
  examples/dsl/v2/column_expand/test_column_expand_predict_job_conf.json
  examples/dsl/v2/column_expand/test_column_expand_predict_job_dsl.json
  examples/pipeline/column_expand/column_expand_testsuite.json
  examples/pipeline/column_expand/pipeline-column-expand.py
  python/federatedml/conf/setting_conf/ColumnExpand.json
Labels: federatedml
