Repository FederatedAI/FATE, pull requests merged in 2021-11, with the labels that each got.

#3266 Feature 1.7 sshe fix bug
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_base.py
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_guest.py
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_host.py
  python/federatedml/nn/hetero_nn/backend/paillier_tensor.py
  python/federatedml/nn/hetero_nn/backend/tf_keras/interactive/dense_model.py
  python/federatedml/nn/hetero_nn/model/interactive_layer.py
  python/federatedml/nn/hetero_nn/test/paillier_tensor_test.py
  python/federatedml/nn/hetero_nn/test/random_number_generator_test.py
  python/federatedml/nn/hetero_nn/util/random_number_generator.py
  python/federatedml/protobuf/generated/lr_model_param_pb2.py
  python/federatedml/protobuf/proto/lr-model-param.proto
  python/federatedml/secureprotol/fixedpoint.py
  python/federatedml/secureprotol/spdz/communicator/federation.py
  python/federatedml/secureprotol/spdz/spdz.py
  python/federatedml/secureprotol/spdz/tensor/fixedpoint_numpy.py
  python/federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
  python/federatedml/secureprotol/spdz/utils/random_utils2.py
  python/federatedml/transfer_learning/hetero_ftl/ftl_base.py
  python/federatedml/transfer_learning/hetero_ftl/ftl_guest.py
  python/federatedml/transfer_learning/hetero_ftl/ftl_host.py
Labels: federatedml

#3269 fix error of sshe-lr examples
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_all_reveal_in_guest_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_compute_loss_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_compute_loss_not_reveal_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_cv_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_l1_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_normal_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_normal_not_fit_intercept_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_l1_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_none_penalty_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_reveal_guest_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_with_validate_conf.json
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-all-reveal-in-guest.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-compute-loss-not-reveal.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-compute-loss.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-cv.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-l1.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-normal-not-fit-intercept.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-normal.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-l1.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-none-penalty.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-reveal-guest.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-with-validate.py
  python/federatedml/nn/hetero_nn/test/paillier_tensor_test.py
  python/federatedml/nn/hetero_nn/test/random_number_generator_test.py
Labels: bug, examples

#3273 Fix SSHE-LR OVR Fit Intercept Saving
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_base.py
Labels: bug

#3271 Feature 1.7 doc update
  .gitignore
  doc/api/index.md
  doc/api/index.zh.md
  doc/deploy
  doc/develop/develop_guide.zh.md
  doc/federatedml_component/index.zh.md
  doc/mkdocs/hook.py
  doc/readthedoc/Makefile
  doc/readthedoc/_static/theme_overrides.css
  doc/readthedoc/_templates/layout.html
  doc/readthedoc/conf.py
  doc/readthedoc/index.rst
  doc/readthedoc/make.bat
  doc/readthedoc/requirements.txt
  doc/resources/index.md
  doc/resources/index.zh.md
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.md
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.zh.md
  doc/tutorial/index.md
  doc/tutorial/model_publish_with_serving_guide.md
  doc/tutorial/model_publish_with_serving_guide.zh.md
  mkdocs.yml
  python/federatedml/param/hetero_sshe_lr_param.py
Labels: document

#3277 fix pipeline param
  python/fate_client/pipeline/param/hetero_sshe_lr_param.py
Labels: federatedml

#3278 update examples
  examples/dsl/v2/hetero_logistic_regression/README.md
  examples/dsl/v2/hetero_logistic_regression/hetero_logistic_regression_testsuite.json
  examples/dsl/v2/hetero_logistic_regression/hetero_lr_warm_start_conf.json
  examples/dsl/v2/hetero_logistic_regression/hetero_lr_warm_start_dsl.json
  examples/pipeline/hetero_logistic_regression/README.md
  examples/pipeline/hetero_logistic_regression/hetero_logistic_regression_pipeline_testsuite.json
  examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-warm-start-old.py
  examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-warm-start.py
Labels: examples

#3279 update doc
  doc/tutorial/pipeline/pipeline_guide.md
  examples/pipeline/demo/pipeline-quick-demo.py
  examples/pipeline/demo/pipeline-upload.py
Labels: document, examples

#3282 Feature 1.7 pipeline param fix
  examples/dsl/v2/hetero_logistic_regression/hetero_lr_ovr_validate_conf.json
  examples/dsl/v2/hetero_logistic_regression/hetero_lr_validate_conf.json
Labels: examples

#3286 edit feature imputation
  python/fate_client/pipeline/param/feature_imputation_param.py
  python/federatedml/feature/feature_imputation.py
  python/federatedml/feature/imputer.py
  python/federatedml/param/feature_imputation_param.py
Labels: examples

#3283 Feature 1.7 sshe fix bug
  python/fate_client/pipeline/param/hetero_sshe_lr_param.py
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_base.py
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_guest.py
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_host.py
  python/federatedml/param/hetero_sshe_lr_param.py
  python/federatedml/secureprotol/encrypt_mode.py
  python/federatedml/secureprotol/spdz/secure_matrix/secure_matrix.py
  python/federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
Labels: bug, federatedml

#3289 edit doc
  README.md
  doc/api/fate_client/pipeline.md
  doc/api/fate_client/pipeline_component.md
  doc/develop/develop_guide.md
  doc/federatedml_component/feldman_verifiable_sum.md
  doc/federatedml_component/index.md
  doc/federatedml_component/index.zh.md
  doc/federatedml_component/secureprotol.md
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.md
  examples/dsl/v2/README.rst
Labels: document

#3293 edit doc
  doc/federatedml_component/feldman_verifiable_sum.md
Labels: document

#3298 Docs/1.7.0/updaate-secureprotol
  doc/api/computing.md
  doc/develop/develop_guide.zh.md
  doc/federatedml_component/column_expand.md
  doc/federatedml_component/correlation.md
  doc/federatedml_component/data_split.md
  doc/federatedml_component/data_transform.md
  doc/federatedml_component/ensemble.md
  doc/federatedml_component/evaluation.md
  doc/federatedml_component/feature_binning.md
  doc/federatedml_component/feature_imputation.md
  doc/federatedml_component/feature_selection.md
  doc/federatedml_component/feldman_verifiable_sum.md
  doc/federatedml_component/hetero_ftl.md
  doc/federatedml_component/hetero_kmeans.md
  doc/federatedml_component/hetero_nn.md
  doc/federatedml_component/homo_nn.md
  doc/federatedml_component/homo_onehot_encoder.md
  doc/federatedml_component/index.md
  doc/federatedml_component/index.zh.md
  doc/federatedml_component/intersect.md
  doc/federatedml_component/label_transform.md
  doc/federatedml_component/linear_regression.md
  doc/federatedml_component/local_baseline.md
  doc/federatedml_component/logistic_regression.md
  doc/federatedml_component/onehot_encoder.md
  doc/federatedml_component/psi.md
  doc/federatedml_component/sample.md
  doc/federatedml_component/sample_weight.md
  doc/federatedml_component/sbt_feature_transformer.md
  doc/federatedml_component/scale.md
  doc/federatedml_component/scorecard.md
  doc/federatedml_component/secureprotol.md
  doc/federatedml_component/sir.md
  doc/federatedml_component/sshe_lr.md
  doc/federatedml_component/statistic.md
  doc/federatedml_component/stepwise.md
  doc/federatedml_component/union.md
  doc/index.md
  doc/index.zh.md
  doc/mkdocs/README.md
  doc/mkdocs/hook.py
  doc/mkdocs/theme/overrides/home.html
  doc/mkdocs/theme/overrides/home.zh.html
  mkdocs.yml
Labels: document

#3302 fix cardinality
  python/federatedml/statistic/intersect/intersect_model.py
  python/federatedml/statistic/intersect/rsa_intersect/rsa_intersect_guest.py
Labels: bug, federatedml

#3305 Feature 1.7 doc examples update
  doc/api/fate_client/pipeline.rst
  doc/federatedml_component/data_split.rst
  doc/federatedml_component/feldman_verifiable_sum.rst
  doc/federatedml_component/intersect.md
  doc/federatedml_component/intersect.rst
  doc/federatedml_component/linear_regression.rst
  doc/federatedml_component/local_baseline.rst
  doc/federatedml_component/logistic_regression.rst
  doc/federatedml_component/params.rst
  doc/federatedml_component/poisson_regression.rst
  doc/federatedml_component/scorecard.md
  doc/federatedml_component/scorecard.rst
  doc/federatedml_component/sir.rst
  doc/federatedml_component/sshe_lr.rst
  doc/federatedml_component/stepwise.rst
  doc/federatedml_component/union.rst
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.zh.md
  doc/tutorial/dsl_conf/upload_data_guide.md
  doc/tutorial/dsl_conf/upload_data_guide.zh.md
  doc/tutorial/pipeline/pipeline_guide.rst
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_encrypted_reveal_in_host_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_encrypted_reveal_in_host_dsl.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_encrypted_reveal_in_host_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_encrypted_reveal_in_host_dsl.json
  examples/dsl/v2/hetero_sshe_lr/hetero_sshe_lr_testsuite.json
  examples/pipeline/hetero_sshe_lr/hetero_sshe_lr_pipeline_testsuite.json
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-encrypted-reveal-in-host.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-encrypted-reveal-in-host.py
Labels: examples

#3306 update intersect
  python/federatedml/statistic/intersect/rsa_intersect/rsa_intersect_guest.py
Labels: federatedml

#3297 edit pipeline
  doc/api/fate_client/pipeline.md
  examples/dsl/v2/intersect/README.md
  examples/dsl/v2/intersect/intersect_testsuite.json
  examples/dsl/v2/intersect/test_intersect_job_cardinality_conf.json
  examples/pipeline/demo/pipeline-deploy-demo.py
  examples/pipeline/intersect/README.md
  examples/pipeline/intersect/intersect_testsuite.json
  examples/pipeline/intersect/pipeline-intersect-cardinality.py
  python/fate_client/pipeline/backend/config.py
  python/fate_client/pipeline/backend/pipeline.py
  python/fate_client/pipeline/config.yaml
  python/fate_client/pipeline/pipeline_cli.py
  python/fate_client/pipeline/utils/invoker/job_submitter.py
Labels: enhancement, document, examples

#3292 avoid hang on consume on rabbitmq
  python/fate_arch/federation/pulsar/_federation.py
  python/fate_arch/federation/pulsar/_mq_channel.py
  python/fate_arch/federation/pulsar/_pulsar_manager.py
  python/fate_arch/federation/rabbitmq/_federation.py
Labels: bug

#3313 fix loss
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/regression_loss.py
Labels: bug

#3311 Feature 1.7 doc examples update
  doc/api/fate_test.md
  examples/benchmark_performance/README.md
  examples/dsl/v2/hetero_sshe_lr/README.md
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_warm_start_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_sshe_lr_testsuite.json
  examples/pipeline/hetero_sshe_lr/README.md
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-warm-start.py
Labels: document, examples

#3315 Develop 1.7 sshe
  python/fate_client/pipeline/param/hetero_sshe_lr_param.py
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_base.py
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_guest.py
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_host.py
  python/federatedml/param/hetero_sshe_lr_param.py
  python/federatedml/secureprotol/encrypt_mode.py
  python/federatedml/secureprotol/spdz/secure_matrix/secure_matrix.py
  python/federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
Labels: bug

#3320 Feature 1.7 intersect cache fix
  python/fate_client/pipeline/param/intersect_param.py
  python/federatedml/param/intersect_param.py
  python/federatedml/statistic/intersect/intersect_model.py
Labels: federatedml

#3328 edit examples
  examples/dsl/v2/model_loader/binning_train_conf.json
  examples/dsl/v2/model_loader/model_loader_conf.json
Labels: examples

#3335 edit doc
  doc/federatedml_component/secureprotol.md
  python/fate_client/pipeline/param/hetero_sshe_lr_param.py
  python/federatedml/param/hetero_sshe_lr_param.py
Labels: document

#3341 update sbt benchmark
  examples/benchmark_quality/hetero_fast_sbt/gbdt-binary.py
  examples/benchmark_quality/hetero_fast_sbt/gbdt-multi.py
  examples/benchmark_quality/hetero_fast_sbt/gbdt-regression.py
  examples/benchmark_quality/hetero_sbt/gbdt-binary.py
  examples/benchmark_quality/hetero_sbt/gbdt-multi.py
  examples/benchmark_quality/hetero_sbt/gbdt-regression.py
  examples/benchmark_quality/homo_sbt/gbdt-binary.py
  examples/benchmark_quality/homo_sbt/gbdt-multi.py
  examples/benchmark_quality/homo_sbt/gbdt-regression.py
Labels: bug

#3348 Feature 1.7 doc examples update
  README.md
  README_zh.md
  doc/api/fate_test.md
  doc/federatedml_component/index.md
  doc/federatedml_component/index.zh.md
  doc/federatedml_component/sshe_lr.md
  doc/tutorial/fate_test_tutorial.md
  examples/benchmark_quality/hetero_lr/vehicle_sshe_lr_config.yaml
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_compute_loss_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_cv_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_l1_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_normal_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_normal_not_fit_intercept_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_l1_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_warm_start_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_with_validate_conf.json
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-compute-loss.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-cv.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-l1.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-normal-not-fit-intercept.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-normal.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-l1.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-warm-start.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-with-validate.py
  python/fate_client/pipeline/param/boosting_param.py
  python/fate_client/pipeline/param/callback_param.py
  python/fate_client/pipeline/param/column_expand_param.py
  python/fate_client/pipeline/param/cross_validation_param.py
  python/fate_client/pipeline/param/data_split_param.py
  python/fate_client/pipeline/param/encrypt_param.py
  python/fate_client/pipeline/param/encrypted_mode_calculation_param.py
  python/fate_client/pipeline/param/feature_imputation_param.py
  python/fate_client/pipeline/param/feldman_verifiable_sum_param.py
  python/fate_client/pipeline/param/hetero_sshe_lr_param.py
  python/fate_client/pipeline/param/init_model_param.py
  python/fate_client/pipeline/param/intersect_param.py
  python/fate_client/pipeline/param/label_transform_param.py
  python/fate_client/pipeline/param/linear_regression_param.py
  python/fate_client/pipeline/param/local_baseline_param.py
  python/fate_client/pipeline/param/logistic_regression_param.py
  python/fate_client/pipeline/param/one_vs_rest_param.py
  python/fate_client/pipeline/param/poisson_regression_param.py
  python/fate_client/pipeline/param/predict_param.py
  python/fate_client/pipeline/param/scale_param.py
  python/fate_client/pipeline/param/scorecard_param.py
  python/fate_client/pipeline/param/sir_param.py
  python/fate_client/pipeline/param/sqn_param.py
  python/fate_client/pipeline/param/stepwise_param.py
  python/federatedml/param/hetero_sshe_lr_param.py
Labels: federatedml, document, examples

#3353 edit examples
  examples/dsl/v2/hetero_logistic_regression/README.md
  examples/dsl/v2/hetero_logistic_regression/hetero_logistic_regression_testsuite.json
  examples/dsl/v2/hetero_logistic_regression/hetero_lr_normal_predict_conf.json
  examples/dsl/v2/hetero_logistic_regression/hetero_lr_normal_predict_dsl.json
  examples/dsl/v2/hetero_sshe_lr/README.md
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_normal_predict_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_normal_predict_dsl.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_predict_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_predict_dsl.json
  examples/dsl/v2/hetero_sshe_lr/hetero_sshe_lr_testsuite.json
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-normal.py
Labels: examples

#3334 Feature/1.7.0/static-default
  python/federatedml/param/base_param.py
Labels: federatedml

#3357 fix optimal binning predict error, add some test cases.
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_converged_weight_diff_encrypted_not_reveal_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_converged_weight_diff_encrypted_not_reveal_dsl.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_converged_weight_diff_respectively_not_reveal_conf.json
  examples/dsl/v2/hetero_sshe_lr/hetero_lr_converged_weight_diff_respectively_not_reveal_dsl.json
  examples/dsl/v2/hetero_sshe_lr/hetero_sshe_lr_testsuite.json
  examples/min_test_task/run_task.py
  examples/pipeline/hetero_sshe_lr/hetero_sshe_lr_pipeline_testsuite.json
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-converged-weight-diff-encrypted-not-reveal.py
  examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-converged-weight-diff-respectively-not-reveal.py
  examples/scripts/upload_default_data.py
  python/federatedml/feature/binning/optimal_binning/optimal_binning.py
  python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_base.py
Labels: bug, federatedml, examples

#3326 Feature 1.7 fix static param and not using bultin md5
  python/federatedml/param/base_param.py
  python/federatedml/secureprotol/spdz/utils/naming.py
Labels: federatedml

#3368 add comments
  doc/api/computing.md
  doc/api/federation.md
  doc/api/session.md
Labels: document

#3371 Feature 1.7 doc examples update
  README.md
  README_zh.md
  doc/api/fate_client/flow_sdk.rst
  doc/api/fate_client/flow_sdk_zh.rst
  doc/api/fate_client/pipeline.md
  doc/tutorial/README.md
  doc/tutorial/dsl_conf/dsl_conf_tutorial.md
  doc/tutorial/pipeline/pipeline_guide.md
  doc/tutorial/pipeline/pipeline_tutorial_hetero_sbt.ipynb
  doc/tutorial/pipeline/pipeline_tutorial_homo_nn.ipynb
  doc/tutorial/pipeline/pipeline_tutorial_upload.ipynb
  examples/README.rst
  examples/README_zh.rst
  examples/benchmark_quality/hetero_lr/vehicle_sshe_lr_config.yaml
  examples/examples_overview.md
  examples/examples_overview.zh.md
  examples/experiment_template/user_usage/dsl_v1_predict_tutorial.md
  examples/experiment_template/user_usage/pipeline_predict_tutorial.md
Labels: document, examples

#3374 Feature 1.7 doc examples update
  doc/tutorial/pipeline/pipeline_tutorial_hetero_sbt.ipynb
  doc/tutorial/pipeline/pipeline_tutorial_upload.ipynb
Labels: document

#3379 fix pipiline predict process bug: which cannot get training component 's taskinfo instance
  examples/dsl/v2/data_transform/README.md
  examples/dsl/v2/data_transform/data_transform_testsuite.json
  examples/dsl/v2/data_transform/test_data_transform_svmlight.json
  examples/dsl/v2/hetero_nn/README.md
  examples/dsl/v2/hetero_nn/hetero_nn_testsuite.json
  examples/pipeline/data_transform/README.md
  examples/pipeline/hetero_nn/README.md
  examples/pipeline/hetero_nn/hetero_nn_testsuite.json
  examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary-with-predict.py
  python/fate_client/pipeline/backend/pipeline.py
  python/federatedml/optim/gradient/test/gradient_method_test.py
Labels: bug

#3391 Fix Binning Bug And BenchMark Quality
  examples/benchmark_quality/hetero_nn/hetero_nn_give_credit_config.yaml
  examples/benchmark_quality/hetero_nn/local-hetero_nn.py
  python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
Labels: bug

#3394 Feature 1.7 doc examples update
  python/fate_test/fate_test/scripts/benchmark_cli.py
  python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
  python/federatedml/model_base.py
  python/federatedml/one_vs_rest/one_vs_rest.py
Labels: bug, enhancement, federatedml

#3398 Feature 1.7 doc examples update
  examples/benchmark_quality/hetero_lr/give_credit_config.yaml
  examples/benchmark_quality/hetero_lr/give_credit_sshe_lr_config.yaml
  python/fate_test/fate_test/scripts/benchmark_cli.py
Labels: enhancement

#3405 Feature 1.7 doc examples update
  deploy/cluster-deploy/doc/fate_on_eggroll/Fate-allinone_deployment_guide_install.md
  deploy/cluster-deploy/doc/fate_on_eggroll/Fate-allinone_deployment_guide_install_zh.md
  python/federatedml/callbacks/validation_strategy.py
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/cross_entropy.py
  python/federatedml/ensemble/boosting/boosting_core/boosting.py
  python/federatedml/feature/binning/base_binning.py
  python/federatedml/feature/binning/bucket_binning.py
  python/federatedml/feature/binning/iv_calculator.py
  python/federatedml/feature/binning/optimal_binning/optimal_binning.py
  python/federatedml/feature/binning/quantile_binning.py
  python/federatedml/feature/feature_selection/filter_base.py
  python/federatedml/feature/feature_selection/percentage_value_filter.py
  python/federatedml/feature/imputer.py
  python/federatedml/feature/sampler.py
  python/federatedml/linear_model/base_linear_model_arbiter.py
  python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_guest.py
  python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
  python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
  python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
  python/federatedml/linear_model/poisson_regression/base_poisson_regression.py
  python/federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
  python/federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_host.py
  python/federatedml/loss/cross_entropy.py
  python/federatedml/one_vs_rest/one_vs_rest.py
  python/federatedml/optim/gradient/hetero_linear_model_gradient.py
  python/federatedml/optim/gradient/hetero_poisson_gradient_and_loss.py
  python/federatedml/secureprotol/encrypt_mode.py
  python/federatedml/statistic/data_overview.py
  python/federatedml/statistic/statics.py
  python/federatedml/transfer_learning/hetero_ftl/ftl_base.py
  python/federatedml/util/abnormal_detection.py
  python/federatedml/util/classify_label_checker.py
Labels: document

#3415 Feature 1.7 doc examples update
  README.md
  README_zh.md
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/README.zh.md
  doc/tutorial/README.md
  doc/tutorial/pipeline/pipeline_tutorial_match_id.ipynb
  doc/tutorial/pipeline/pipeline_tutorial_upload.ipynb
  python/fate_test/fate_test/scripts/quick_test_cli.py
  python/federatedml/feature/feature_selection/test/outlier_filter_test.py
  python/federatedml/feature/feature_selection/test/variance_coe_filter_test.py
Labels: document

#3419 Feature 1.7 doc examples update
  README.md
  README_zh.md
  doc/api/fate_client/pipeline_component.md
  doc/api/fate_client/pipeline_component.rst
  doc/federatedml_component/README.md
  doc/federatedml_component/README.zh.md
  doc/federatedml_component/correlation.rst
  doc/federatedml_component/ensemble.rst
  doc/federatedml_component/evaluation.rst
  doc/federatedml_component/hetero_ftl.rst
  doc/federatedml_component/hetero_kmeans.rst
  doc/federatedml_component/hetero_nn.rst
  doc/federatedml_component/linear_regression.md
  doc/federatedml_component/logistic_regression.md
  doc/federatedml_component/psi.rst
  doc/federatedml_component/secureprotol.rst
  doc/federatedml_component/statistic.rst
  doc/federatedml_component/util.rst
Labels: document

#3425 update homo nn examples
  examples/dsl/v2/homo_nn/README.md
  examples/dsl/v2/homo_nn/homo_nn_dsl.json
  examples/dsl/v2/homo_nn/keras_homo_dnn_multi_label.json
  examples/dsl/v2/homo_nn/keras_homo_dnn_multi_layer.json
  examples/dsl/v2/homo_nn/keras_homo_dnn_multi_layer_predict.json
  examples/dsl/v2/homo_nn/keras_homo_dnn_single_layer.json
  examples/dsl/v2/homo_nn/keras_homo_nn_testsuite.json
  examples/dsl/v2/homo_nn/pytorch_homo_dnn_multi_label.json
  examples/dsl/v2/homo_nn/pytorch_homo_dnn_multi_layer.json
  examples/dsl/v2/homo_nn/pytorch_homo_dnn_single_layer.json
  examples/dsl/v2/homo_nn/pytorch_homo_nn_testsuite.json
  examples/dsl/v2/homo_nn/test_homo_dnn_multi_layer_dsl.json
  examples/dsl/v2/homo_nn/test_homo_dnn_multi_layer_predict_dsl.json
  examples/dsl/v2/homo_nn/test_homo_dnn_single_layer_dsl.json
Labels: examples

#3437 Feature 1.7 fix examples
  examples/benchmark_quality/hetero_lr/pipeline-lr-multi.py
  examples/benchmark_quality/homo_lr/pipeline-lr-binary.py
  examples/dsl/v2/hetero_pearson/hetero_pearson_testsuite.json
  examples/dsl/v2/homo_nn/mnist_demo/upload.json
  examples/dsl/v2/upload/upload_conf.json
  examples/dsl/v2/upload/upload_tag_conf.json
  examples/pipeline/hetero_ftl/pipeline-hetero-ftl-communication-efficient.py
  examples/pipeline/hetero_ftl/pipeline-hetero-ftl-encrypted.py
  examples/pipeline/hetero_ftl/pipeline-hetero-ftl-plain.py
  examples/pipeline/hetero_pearson/hetero_pearson_testsuite.json
  examples/pipeline/intersect/pipeline-intersect-with-union.py
Labels: examples

#3440 fix doc of standalone-deploy
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/README.zh.md
  deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.md
  deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.zh.md
Labels: bug, document

#3445 fix badge
  README.md
  README_zh.md
Labels: document

#3448 Feature 1.7 fix examples
  doc/api/fate_client/pipeline.md
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.md
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.zh.md
  doc/tutorial/dsl_conf/upload_data_guide.md
  doc/tutorial/dsl_conf/upload_data_guide.zh.md
  examples/dsl/v2/homo_nn/mnist_demo/README.md
  examples/dsl/v2/homo_nn/mnist_demo/bind_local_path.json
  examples/dsl/v2/homo_nn/mnist_demo/upload.json
Labels: examples

#3451 edit doc
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.md
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.zh.md
  doc/tutorial/dsl_conf/upload_data_guide.md
  doc/tutorial/dsl_conf/upload_data_guide.zh.md
Labels: document

#3453 edit doc
  README.md
Labels: document

#3456 fix doc of federatedml_components readme
  doc/federatedml_component/README.md
  doc/federatedml_component/README.zh.md
Labels: document

#3458 Feature 1.7 doc examples update
  README.md
  README_zh.md
  doc/federatedml_component/README.md
  doc/federatedml_component/README.zh.md
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.md
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.zh.md
  doc/tutorial/pipeline/pipeline_tutorial_hetero_sbt.ipynb
  doc/tutorial/pipeline/pipeline_tutorial_match_id.ipynb
Labels: document

#3460 edit doc
  python/fate_client/pipeline/param/hetero_sshe_lr_param.py
  python/federatedml/param/hetero_sshe_lr_param.py
Labels: document

#3461 fix develop guide
  doc/develop/develop_guide.md
  doc/develop/develop_guide.zh.md
Labels: document

#3473 Fix Standalone deploy doc
  RELEASE.md
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/README.zh.md
  deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.md
Labels: bug, document

#3472 fix ensemble format
  doc/federatedml_component/ensemble.md
Labels: document

#3476 fix standalone deploy doc
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.md
  deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.zh.md
Labels: document

#3479 add build as softlink to doc to fix some links issue
  doc/build
Labels: document

#3486 add `__rmul__` and `__radd__` in weights
  python/federatedml/framework/weights.py
Labels: enhancement
