Repository FederatedAI/FATE, pull requests merged in 2021-12, with the labels that each got.

#3495 update fate_test doc
  doc/tutorial/fate_test_tutorial.md
Labels: bug, document

#3482 Action/1.7.0/code-format
  .flake8
  .github/workflows/autopep8-command.yml
  .github/workflows/autopep8-suggester.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/fate-test-command.yml
  .github/workflows/slash-command-dispatch.yml
Labels: CI

#3502 ignore some file from autopep8
  .flake8
  python/federatedml/secureprotol/symmetric_encryption/py_aes_core.py
Labels: CI

#3504 update dev doc. Add __init__
  doc/develop/develop_guide.md
  doc/develop/develop_guide.zh.md
Labels: document

#3493 Fix bugs that using the standalone install in Ubuntu
  bin/common.sh
  bin/install_os_dependencies.sh
  build/package-build/build.sh
  build/standalone-docker-build/base/python/init.sh
  build/standalone-docker-build/build.sh
  build/standalone-docker-build/docker-entrypoint.sh
  build/standalone-install-build/build.sh
  build/standalone-install-build/init.sh
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/README.zh.md
  deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.md
  deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.zh.md
Labels: bug, deploy

#3514 update doc
  doc/federatedml_component/intersect.md
Labels: document

#3524 update the path of pic in doc
  doc/federatedml_component/homo_framework.md
Labels: document

#3513 fix homo_lr learning_rate decay bug
  .github/workflows/autopep8-command.yml
  python/fate_arch/storage/_session.py
  python/fate_client/flow_client/flow_cli/utils/cli_utils.py
  python/fate_test/fate_test/flow_test/flow_cli_api.py
  python/fate_test/fate_test/flow_test/flow_sdk_api.py
  python/federatedml/evaluation/metric_interface.py
  python/federatedml/framework/weights.py
  python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_host.py
Labels: bug

#3525 fix #3516
  python/fate_client/flow_client/flow_cli/utils/cli_utils.py
Labels: bug

#3532 update pipeline.md
  doc/api/fate_client/pipeline.md
Labels: document

#3533 Fix3531
  python/federatedml/linear_model/linear_model_weight.py
Labels: bug

#3547 Feature 1.8 statistics
  python/federatedml/secure_information_retrieval/base_secure_information_retrieval.py
  python/federatedml/secure_information_retrieval/secure_information_retrieval_guest.py
  python/federatedml/statistic/data_statistics.py
  python/federatedml/statistic/statics.py
Labels: enhancement, federatedml

#3551 edit stats
  python/federatedml/statistic/statics.py
Labels: enhancement, federatedml

#3548 fixed spdz default encoder bugs
  python/federatedml/secureprotol/spdz/tensor/fixedpoint_endec.py
  python/federatedml/secureprotol/spdz/tensor/fixedpoint_numpy.py
  python/federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
Labels: bug

#3554 add cache to `count`
  python/fate_arch/computing/eggroll/_table.py
  python/fate_arch/computing/spark/_table.py
  python/fate_arch/computing/standalone/_table.py
Labels: feature-request

#3586 edit stats & sir
  python/federatedml/secure_information_retrieval/base_secure_information_retrieval.py
  python/federatedml/secure_information_retrieval/secure_information_retrieval_guest.py
  python/federatedml/statistic/data_statistics.py
  python/federatedml/statistic/statics.py
Labels: bug, enhancement, federatedml
