Repository FederatedAI/FATE, pull requests merged in 2022-04, with the labels that each got.

#3840 fix doc and examples
  doc/api/fate_test.md
  doc/develop/develop_guide.md
  doc/develop/develop_guide.zh.md
  doc/tutorial/dsl_conf/dsl_conf_tutorial.md
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.md
  doc/tutorial/dsl_conf/dsl_conf_v2_setting_guide.zh.md
  doc/tutorial/fate_test_tutorial.md
  examples/dsl/v2/data_split/test_hetero_data_split_job_conf.json
  examples/dsl/v2/data_split/test_hetero_data_split_multi_model_job_conf.json
  examples/dsl/v2/hetero_linear_regression/test_hetero_linr_warm_start_job_conf.json
  examples/dsl/v2/hetero_poisson_regression/test_hetero_poisson_warm_start_job_conf.json
  examples/dsl/v2/hetero_sshe_linr/hetero_linr_compute_loss_not_reveal_conf.json
  examples/dsl/v2/hetero_sshe_linr/hetero_linr_conf.json
  examples/dsl/v2/hetero_sshe_linr/hetero_linr_cv_conf.json
  examples/dsl/v2/hetero_sshe_linr/hetero_linr_encrypted_reveal_in_host_conf.json
  examples/dsl/v2/hetero_sshe_linr/hetero_linr_large_init_w_compute_loss_conf.json
  examples/dsl/v2/hetero_sshe_linr/hetero_linr_sample_weight_conf.json
  examples/dsl/v2/hetero_sshe_linr/hetero_linr_validate_conf.json
  examples/dsl/v2/hetero_sshe_linr/hetero_linr_warm_start_conf.json
  examples/pipeline/data_split/pipeline-hetero-data-split-multi-model.py
  examples/pipeline/data_split/pipeline-hetero-data-split.py
  examples/pipeline/hetero_sshe_linr/pipeline-hetero-linr-compute-loss-not-reveal.py
  examples/pipeline/hetero_sshe_linr/pipeline-hetero-linr-cv.py
  examples/pipeline/hetero_sshe_linr/pipeline-hetero-linr-encrypted-reveal-in-host.py
  examples/pipeline/hetero_sshe_linr/pipeline-hetero-linr-large-init-w-compute-loss.py
  examples/pipeline/hetero_sshe_linr/pipeline-hetero-linr-sample-weight.py
  examples/pipeline/hetero_sshe_linr/pipeline-hetero-linr-validate.py
  examples/pipeline/hetero_sshe_linr/pipeline-hetero-linr-warm-start.py
  examples/pipeline/hetero_sshe_linr/pipeline-hetero-linr.py
  examples/pipeline/label_transform/pipeline-label-transform.py
  examples/pipeline/match_id_test/pipeline-label-transform.py
  python/fate_client/pyproject.toml
  python/fate_client/setup.py
  python/fate_test/fate_test/scripts/cli.py
  python/fate_test/pyproject.toml
  python/fate_test/setup.py
Labels: document, examples

#3844 edit upload data logic of allInOne deploy doc
  deploy/cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide.md
  deploy/cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide.zh.md
Labels: document

#3851 Feature 1.8 fix fast sbt pipeline
  examples/benchmark_quality/hetero_sbt/fate-sbt.py
  examples/benchmark_quality/hetero_sbt/fate_sbt_multi_mo.yaml
  examples/benchmark_quality/hetero_sbt/fate_sbt_multi_so.yaml
  examples/benchmark_quality/hetero_sbt/hetero_sbt_gbdt_benchmark.json
  python/federatedml/ensemble/test/gh_packing_compressing_test.py
Labels: bug

#3850 Feature 1.8 sshe glm update
  examples/benchmark_quality/hetero_linear_regression/fate-sshe-linr.py
  examples/benchmark_quality/hetero_linear_regression/hetero_linr_benchmark.json
  examples/benchmark_quality/hetero_linear_regression/sshe_linr_config.yaml
  python/fate_test/fate_test/_parser.py
  python/fate_test/fate_test/scripts/testsuite_cli.py
  python/federatedml/linear_model/bilateral_linear_model/hetero_sshe_linear_model.py
  python/federatedml/linear_model/bilateral_linear_model/hetero_sshe_linear_regression/hetero_linr_guest.py
Labels: enhancement, federatedml, examples

#3869 update init.sh
  build/standalone-install-build/init.sh
Labels: bug

#3870 update init.sh
  build/standalone-install-build/init.sh
Labels: bug

#3872 optim federation and raise exception
  python/fate_arch/federation/pulsar/_federation.py
  python/fate_arch/federation/pulsar/_mq_channel.py
  python/fate_arch/federation/rabbitmq/_mq_channel.py
Labels: bug

#3873 Feature 1.8 fix sbt unitest
  python/federatedml/ensemble/test/gh_packing_compressing_test.py
Labels: bug

#3874 fix checks
  .flake8
  doc/mkdocs/requirements.txt
  python/federatedml/linear_model/bilateral_linear_model/hetero_sshe_linear_regression/hetero_linr_guest.py
  python/federatedml/linear_model/bilateral_linear_model/hetero_sshe_linear_regression/hetero_linr_host.py
  python/federatedml/protobuf/generated/poisson_model_meta_pb2.py
  python/federatedml/statistic/statics.py
Labels: bug

#3876 Feature 1.8 sshe glm update
  examples/dsl/v2/hetero_sshe_linr/hetero_linr_large_init_w_compute_loss_conf.json
  examples/pipeline/hetero_sshe_linr/pipeline-hetero-linr-large-init-w-compute-loss.py
  python/federatedml/linear_model/bilateral_linear_model/hetero_sshe_linear_regression/hetero_linr_host.py
Labels: document, examples

#3881 upload dh_intersection and multi_host_dh_intersection interpretation images
  doc/images/dh_intersection.png
  doc/images/multi_host_dh_intersection.png
Labels: document

#3886 edit doc (#3766)
  doc/federatedml_component/intersect.md
Labels: document

#3889 update docker deploy doc
  build/standalone-docker-build/docker-entrypoint.sh
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/README.zh.md
Labels: deploy, docker build

#3897 Feature 1.8 fix homo binning
  examples/benchmark_quality/homo_sbt/fate-sbt.py
  examples/benchmark_quality/homo_sbt/fate_sbt_multi.yaml
  python/federatedml/feature/binning/quantile_summaries.py
  python/federatedml/feature/homo_feature_binning/homo_binning_base.py
Labels: bug, examples

#3900 add return for commpute_session stop api.
  python/fate_arch/session/_session.py
Labels: bug

#3905 update release note of fate-v1.8
  RELEASE.md
Labels: document

#3913 add multi-class dsl examples for homo-logistic-regression
  doc/federatedml_component/secureprotol.md
  examples/benchmark_quality/homo_lr/homo_lr_sklearn_benchmark.json
  examples/benchmark_quality/homo_lr/pipeline-lr-multi.py
  examples/benchmark_quality/homo_lr/sklearn-lr-multi.py
  examples/benchmark_quality/homo_lr/vehicle_lr_config.yaml
  examples/dsl/v2/homo_logistic_regression/README.md
  examples/dsl/v2/homo_logistic_regression/homo_logistic_regression_testsuite.json
  examples/dsl/v2/homo_logistic_regression/homo_lr_one_vs_all_conf.json
  examples/dsl/v2/homo_logistic_regression/homo_lr_one_vs_all_dsl.json
  examples/dsl/v2/homo_logistic_regression/homo_lr_one_vs_all_encrypted_host_conf.json
  examples/dsl/v2/homo_logistic_regression/homo_lr_one_vs_all_encrypted_host_dsl.json
  examples/pipeline/homo_logistic_regression/README.md
  examples/pipeline/homo_logistic_regression/homo_logistic_regression_pipeline_testsuite.json
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-one-vs-all-encrypted-host.py
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-one-vs-all.py
  python/federatedml/ensemble/test/gh_packing_compressing_test.py
  python/federatedml/linear_model/coordinated_linear_model/logistic_regression/homo_logistic_regression/homo_lr_arbiter.py
  python/federatedml/linear_model/coordinated_linear_model/logistic_regression/homo_logistic_regression/homo_lr_base.py
  python/federatedml/linear_model/coordinated_linear_model/logistic_regression/homo_logistic_regression/homo_lr_host.py
  python/federatedml/secureprotol/__init__.py
  python/federatedml/secureprotol/encrypt.py
Labels: examples

#3916 edit doc (#3766)
  python/fate_client/README.rst
Labels: document
