Repository FederatedAI/FATE, pull requests merged in 2022-12, with the labels that each got.

#4511 Feature 1.10 round2 bug fix
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-binary-coae.py
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-binary-drop-out.py
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-binary-multi-host.py
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-binary-selective-bp.py
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-binary.py
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-multi.py
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-with-check-point.py
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-with-early-stop.py
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-with-warm_start.py
  python/fate_client/pipeline/component/hetero_nn.py
  python/fate_client/pipeline/component/nn/backend/torch/optim.py
  python/fate_client/pipeline/param/logistic_regression_param.py
  python/federatedml/ensemble/boosting/homo_boosting.py
  python/federatedml/ensemble/secureboost/homo_secureboost/homo_secureboost_client.py
  python/federatedml/linear_model/coordinated_linear_model/logistic_regression/homo_logistic_regression/homo_lr_client.py
  python/federatedml/linear_model/coordinated_linear_model/logistic_regression/homo_logistic_regression/homo_lr_server.py
  python/federatedml/nn/backend/torch/optim.py
  python/federatedml/nn/dataset/base.py
  python/federatedml/nn/hetero/base.py
  python/federatedml/nn/hetero/guest.py
  python/federatedml/nn/hetero/interactive/he_interactive_layer.py
  python/federatedml/nn/hetero/model.py
  python/federatedml/nn/hetero/nn_component/bottom_model.py
  python/federatedml/param/logistic_regression_param.py
  python/federatedml/protobuf/homo_model_convert/homo_model_convert.py
  python/federatedml/protobuf/homo_model_convert/pytorch/nn.py
Labels: federatedml

#4515 fix homo-lr
  examples/pipeline/hetero_nn/hetero_nn_testsuite.json
  examples/pipeline/homo_logistic_regression/homo_logistic_regression_pipeline_testsuite.json
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-cv.py
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-eval.py
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-multi-host.py
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-one-vs-all-encrypted-host.py
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-one-vs-all.py
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-sample-weights.py
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-train-eval.py
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-train.py
  examples/pipeline/homo_logistic_regression/pipeline-homo-lr-warm-start.py
  python/federatedml/linear_model/coordinated_linear_model/logistic_regression/homo_logistic_regression/homo_lr_base.py
  python/federatedml/nn/homo/trainer/fedavg_trainer.py
  python/federatedml/param/homo_nn_param.py
Labels: bug, federatedml

#4518 edit transfer var
  python/federatedml/framework/hetero/procedure/paillier_cipher.py
  python/federatedml/framework/hetero/sync/paillier_keygen_sync.py
  python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
  python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
  python/federatedml/transfer_variable/transfer_class/hetero_lr_transfer_variable.py
Labels: enhancement, federatedml

#4519 Feature 1.10 homo lr fix
  python/fate_client/pipeline/component/__init__.py
  python/fate_client/pipeline/component/hetero_nn.py
  python/fate_client/pipeline/component/homo_nn.py
  python/federatedml/nn/homo/client.py
  python/federatedml/nn/homo/trainer/fedavg_trainer.py
Labels: bug

#4523 fix nn pipeline bug
  examples/dsl/v2/hetero_nn/README.md
  examples/dsl/v2/hetero_nn/hetero_nn_testsuite.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_binary_coae_conf.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_binary_conf.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_binary_drop_out_conf.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_binary_multi_host_conf.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_binary_selective_bp_conf.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_multi_conf.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_with_check_point_conf.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_with_check_point_dsl.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_with_early_stop_conf.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_with_early_stop_dsl.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_with_warm_start_conf.json
  examples/dsl/v2/hetero_nn/hetero_nn_train_with_warm_start_dsl.json
  examples/dsl/v2/homo_nn/README.md
  examples/dsl/v2/homo_nn/homo_nn_aggregate_n_epoch_conf.json
  examples/dsl/v2/homo_nn/homo_nn_train_binary_conf.json
  examples/dsl/v2/homo_nn/homo_nn_train_multi_conf.json
  examples/dsl/v2/homo_nn/homo_nn_train_regression_conf.json
  python/fate_client/pipeline/component/homo_nn.py
Labels: bug

#4526 update example
  examples/pipeline/sample_weight/pipeline-sample-weight-name.py
Labels: examples

#4528 edit examples
  examples/dsl/v2/homo_onehot/homo_onehot_string_test_conf.json
  examples/dsl/v2/homo_onehot/homo_onehot_test_conf.json
  examples/pipeline/homo_onehot/pipeline-homo-onehot-string-test.py
  examples/pipeline/homo_onehot/pipeline-homo-onehot-test.py
Labels: examples

#4530 edit unittest
  python/federatedml/local_baseline/test/local_baseline_test.py
Labels: federatedml

#4533 Feature 1.10 final bug fix
  python/fate_client/pipeline/component/homo_nn.py
  python/fate_client/pipeline/component/nn/backend/torch/cust_model.py
  python/fate_client/pipeline/component/nn/backend/torch/serialization.py
  python/federatedml/linear_model/coordinated_linear_model/logistic_regression/homo_logistic_regression/homo_lr_client.py
  python/federatedml/nn/backend/torch/serialization.py
  python/federatedml/nn/backend/utils/data.py
  python/federatedml/nn/dataset/table.py
  python/federatedml/nn/hetero/guest.py
  python/federatedml/nn/homo/client.py
  python/federatedml/nn/homo/trainer/fedavg_trainer.py
  python/federatedml/nn/homo/trainer/trainer_base.py
Labels: bug

#4534 fix unittest
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/test/regression_loss_test.py
  python/federatedml/protobuf/homo_model_convert/test/homo_nn_test.py
Labels: bug

#4536 remove ipcl import warning
  python/federatedml/secureprotol/encrypt.py
Labels: federatedml

#4537 Feature 1.10 ipcl import
  python/fate_client/pipeline/__init__.py
  python/fate_client/pipeline/component/hetero_nn.py
  python/fate_client/pipeline/config.yaml
Labels: bug

#4546 update pypi requirements and remove min_test_task
  examples/min_test_task/README.rst
  examples/min_test_task/__init__.py
  examples/min_test_task/config/__init__.py
  examples/min_test_task/config/bind_model_service.json
  examples/min_test_task/config/download.json
  examples/min_test_task/config/publish_load_model.json
  examples/min_test_task/config/test_hetero_lr_train_job_conf.json
  examples/min_test_task/config/test_hetero_lr_train_job_dsl.json
  examples/min_test_task/config/test_intersect_job_conf.json
  examples/min_test_task/config/test_intersect_job_dsl.json
  examples/min_test_task/config/test_predict_conf.json
  examples/min_test_task/config/test_secureboost_train_binary_conf.json
  examples/min_test_task/config/test_secureboost_train_dsl.json
  examples/min_test_task/config/upload.json
  examples/min_test_task/run_task.py
  python/requirements.txt
Labels: deploy

#4548 update release note of fate-v1.10.0
  RELEASE.md
Labels: document

#4552 pipeline fix
  python/fate_client/pipeline/component/nn/backend/torch/base.py
  python/fate_client/pipeline/component/nn/interface.py
  python/federatedml/nn/backend/torch/base.py
Labels: bug

#4555 update release note of v1.10.0
  RELEASE.md
Labels: document

#4556 edit requirements
  python/requirements.txt
Labels: federatedml

#4559 add CTR doc for FATE-1.10
  doc/tutorial/pipeline/nn_tutorial/CTR-example.ipynb
Labels: document

#4558 Feature 1.10 nn doc pr
  README.md
  README_zh.md
  doc/tutorial/pipeline/nn_tutorial/Bert-example.ipynb
  doc/tutorial/pipeline/nn_tutorial/CTR-example.ipynb
  doc/tutorial/pipeline/nn_tutorial/Hetero-NN-Customize-Dataset.ipynb
  doc/tutorial/pipeline/nn_tutorial/Hetero-NN-Customize-Model.ipynb
  doc/tutorial/pipeline/nn_tutorial/Hetero-NN-Mix-Task.ipynb
  doc/tutorial/pipeline/nn_tutorial/Hetero-NN-Quick-Start.ipynb
  doc/tutorial/pipeline/nn_tutorial/Homo-NN-Customize-Loss.ipynb
  doc/tutorial/pipeline/nn_tutorial/Homo-NN-Customize-Model.ipynb
  doc/tutorial/pipeline/nn_tutorial/Homo-NN-Customize-Trainer.ipynb
  doc/tutorial/pipeline/nn_tutorial/Homo-NN-Customize-your-Dataset.ipynb
  doc/tutorial/pipeline/nn_tutorial/Homo-NN-Quick-Start.ipynb
  doc/tutorial/pipeline/nn_tutorial/Homo-NN-Trainer-Interfaces.ipynb
  doc/tutorial/pipeline/nn_tutorial/Homo-NN-aggregator.ipynb
  doc/tutorial/pipeline/nn_tutorial/Introduce-Built-In-Dataset.ipynb
  doc/tutorial/pipeline/nn_tutorial/README.md
  doc/tutorial/pipeline/nn_tutorial/Resnet-example.ipynb
  examples/benchmark_quality/hetero_nn/fate-hetero_nn.py
  examples/benchmark_quality/hetero_nn/hetero_nn_benchmark.json
  examples/benchmark_quality/hetero_nn/hetero_nn_breast_config.yaml
  examples/benchmark_quality/hetero_nn/hetero_nn_default_credit_config.yaml
  examples/benchmark_quality/hetero_nn/hetero_nn_epsilon_5k_config.yaml
  examples/benchmark_quality/hetero_nn/hetero_nn_give_credit_config.yaml
  examples/benchmark_quality/hetero_nn/hetero_nn_vehicle_scale_config.yaml
  examples/benchmark_quality/hetero_nn/local-hetero_nn.py
  examples/benchmark_quality/homo_lr/give_credit_lr_config.yaml
  examples/benchmark_quality/homo_lr/give_credit_pipeline_lr_config.yaml
  examples/benchmark_quality/homo_lr/homo_lr_sklearn_benchmark.json
  examples/benchmark_quality/homo_lr/pipeline-lr-binary.py
  examples/benchmark_quality/homo_lr/pipeline-lr-multi.py
  examples/benchmark_quality/homo_lr/sklearn-lr-multi.py
  examples/benchmark_quality/homo_lr/vehicle_lr_config.yaml
  examples/benchmark_quality/homo_nn/fate-homo_nn.py
  examples/benchmark_quality/homo_nn/homo_nn_benchmark.json
  examples/benchmark_quality/homo_nn/local-homo_nn.py
  examples/benchmark_quality/homo_nn/param_conf_binary.yaml
  examples/benchmark_quality/homo_nn/param_conf_multi.yaml
  examples/dsl/v2/hetero_nn/hetero_nn_train_with_check_point_conf.json
  examples/dsl/v2/homo_logistic_regression/homo_logistic_regression_testsuite.json
  examples/dsl/v2/homo_logistic_regression/homo_lr_one_vs_all_encrypted_host_conf.json
  examples/dsl/v2/homo_logistic_regression/homo_lr_one_vs_all_encrypted_host_dsl.json
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-with-check-point.py
  python/federatedml/nn/dataset/table.py
Labels: bug, federatedml, document

#4563 update fate_client requirements
  python/fate_client/pyproject.toml
  python/fate_client/setup.py
Labels: deploy

#4564 update requirements
  python/requirements.txt
Labels: deploy
