Repository FederatedAI/FATE, pull requests merged in 2022-08, with the labels that each got.

#4163 Feature 1.9 intersect update
  python/federatedml/statistic/intersect/intersect_model.py
Labels: enhancement, federatedml

#4161 Feature 1.9.0 test round1 bug fix
  python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
  python/federatedml/feature/hetero_feature_binning/hetero_binning_host.py
Labels: bug

#4167 Feature 1.9.0 test round1 bug fix
  python/federatedml/util/data_transform.py
Labels: bug

#4168 remove log
  python/federatedml/ensemble/secureboost/secureboost_util/boosting_tree_predict.py
Labels: bug

#4165 fix: support nan output
  python/federatedml/statistic/correlation/hetero_pearson.py
Labels: bug, enhancement, federatedml

#4174 fix nn warm start bugs
  python/fate_client/pipeline/component/nn/backend/fate_torch/base.py
  python/fate_client/pipeline/component/nn/backend/fate_torch/serialization.py
  python/fate_client/pipeline/param/hetero_nn_param.py
  python/federatedml/nn/backend/fate_torch/base.py
  python/federatedml/nn/backend/fate_torch/serialization.py
  python/federatedml/nn/hetero_nn/model/hetero_nn_model.py
  python/federatedml/nn/hetero_nn/model/interactive_layer.py
  python/federatedml/param/hetero_nn_param.py
Labels: bug

#4177 Feature 1.9.0 fate flow anonymous
  python/fate_arch/common/base_utils.py
  python/fate_arch/protobuf/proto/basic-meta.proto
  python/fate_arch/protobuf/proto/proxy.proto
  python/fate_arch/protobuf/python/fate_meta_pb2.py
  python/fate_arch/protobuf/python/fate_proxy_pb2.py
  python/fate_arch/protobuf/python/fate_proxy_pb2_grpc.py
  python/fate_client/flow_client/flow_cli/utils/cli_utils.py
  python/fate_client/pipeline/param/data_transform_param.py
  python/federatedml/param/data_transform_param.py
  python/federatedml/util/anonymous_generator_util.py
  python/federatedml/util/data_format_preprocess.py
  python/federatedml/util/data_transform.py
Labels: arch

#4179 fix anonymous when using tag&svmlight data format
  python/federatedml/util/data_format_preprocess.py
  python/federatedml/util/data_transform.py
Labels: bug

#4181 fix sm3 base64(#4180)
  examples/dsl/v2/intersect/test_intersect_job_raw_sm3_conf.json
  examples/pipeline/intersect/pipeline-intersect-raw-sm3.py
  python/federatedml/secureprotol/hash/hash_factory.py
Labels: bug, federatedml

#4184 fix import
  python/fate_client/setup.py
Labels: bug

#4186 Feature 1.9 column expand anonymous edit
  examples/dsl/v2/column_expand/README.md
  examples/dsl/v2/column_expand/column_expand_testsuite.json
  examples/dsl/v2/column_expand/test_column_expand_anonymous_job_conf.json
  examples/dsl/v2/upload/README.md
  examples/dsl/v2/upload/upload_anonymous_conf.json
  examples/pipeline/column_expand/README.md
  examples/pipeline/column_expand/column_expand_testsuite.json
  examples/pipeline/column_expand/pipeline-column-expand-anonymous.py
  examples/pipeline/upload/README.md
  examples/pipeline/upload/pipeline-upload-anonymous.py
  python/fate_client/pipeline/backend/pipeline.py
  python/federatedml/feature/column_expand.py
  python/federatedml/feature/hetero_feature_selection/base_feature_selection.py
  python/federatedml/util/data_format_preprocess.py
Labels: enhancement, federatedml

#4187 support get role and party_id from anonymous column
  python/federatedml/util/anonymous_generator_util.py
Labels: federatedml

#4188 Feature 1.9.0 fix pipeline fate torch
  python/fate_client/setup.py
Labels: bug

#4193 add compatibility for dataio transformation
  python/federatedml/util/data_io.py
  python/federatedml/util/data_transform.py
Labels: federatedml

#4195 add clean header interface in data format preprocess
  python/federatedml/util/data_format_preprocess.py
Labels: federatedml

#4196 edit column expand(#3860)
  python/federatedml/components/column_expand.py
  python/federatedml/feature/column_expand.py
  python/federatedml/statistic/intersect/intersect_model.py
Labels: enhancement, federatedml

#4197 Feature 1.9 sbt anonymous migrate fix
  python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
  python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
Labels: bug

#4198 fix load feature importance
  python/federatedml/ensemble/boosting/boosting.py
  python/federatedml/ensemble/boosting/hetero_boosting.py
  python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
  python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
Labels: bug

#4203 remove dataio import
  python/federatedml/model_selection/data_split/data_split.py
  python/federatedml/model_selection/stepwise/step.py
  python/federatedml/model_selection/stepwise/test/stepwise_test.py
Labels: bug, federatedml

#4204 fix data_transform exclusive data type and need_run=False parsing model error
  python/federatedml/util/data_transform.py
Labels: bug

#4206 homo sbt sklearn update
  python/federatedml/ensemble/basic_algorithms/decision_tree/homo/homo_decision_tree_client.py
  python/federatedml/evaluation/metrics/classification_metric.py
Labels: bug, federatedml

#4208 upgrade python requirments from 3.6.5 to python3.8+
  python/fate_client/pyproject.toml
  python/fate_client/setup.py
  python/fate_test/pyproject.toml
  python/fate_test/setup.py
  python/requirements.txt
Labels: enhancement, dependencies, deploy

#4212 refactor: lazy import torchvision
  python/fate_test/fate_test/scripts/data_cli.py
Labels: test

#4209 warm start header alignment
  python/federatedml/__init__.py
  python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
  python/federatedml/feature/feature_selection/model_adapter/tree_adapter.py
  python/federatedml/util/consts.py
Labels: bug

#4214 Feature 1.9 column expand anonymous edit
  examples/dsl/v2/hetero_feature_selection/hetero_feature_selection_testsuite.json
  examples/pipeline/hetero_feature_selection/README.md
  examples/pipeline/hetero_feature_selection/hetero_feature_selection_pipeline_testsuite.json
  python/fate_client/pipeline/backend/pipeline.py
  python/fate_client/pipeline/param/feature_selection_param.py
  python/federatedml/feature/feature_selection/selection_properties.py
  python/federatedml/feature/hetero_feature_selection/base_feature_selection.py
  python/federatedml/param/feature_selection_param.py
  python/federatedml/transfer_variable/transfer_class/hetero_feature_selection_transfer_variable.py
Labels: enhancement, federatedml, document, examples

#4215 Feature 1.9.0 test round2 bug fix
  python/federatedml/util/anonymous_generator_util.py
  python/federatedml/util/data_io.py
  python/federatedml/util/data_transform.py
Labels: bug, enhancement, federatedml

#4217 Intersect add sync match_id(#4216)
  python/federatedml/statistic/intersect/intersect_model.py
  python/federatedml/transfer_variable/transfer_class/intersection_func_transfer_variable.py
Labels: enhancement, federatedml

#4218 Front-end dependent duplicate installation
  build/package-build/build.sh
Labels: fateboard

#4219 update ret
  python/federatedml/feature/feature_selection/model_adapter/tree_adapter.py
Labels: bug

#4223 Feature 1.9 column expand anonymous edit
  doc/federatedml_component/feature_selection.md
  examples/dsl/v2/hetero_feature_selection/hetero_feature_selection_homo_sbt_conf.json
  examples/dsl/v2/hetero_feature_selection/hetero_feature_selection_homo_sbt_dsl.json
  examples/dsl/v2/hetero_feature_selection/hetero_feature_selection_testsuite.json
  examples/pipeline/hetero_feature_selection/README.md
  examples/pipeline/hetero_feature_selection/hetero_feature_selection_pipeline_testsuite.json
  examples/pipeline/hetero_feature_selection/pipeline-hetero-feature-selection-homo-sbt.py
  python/federatedml/feature/column_expand.py
Labels: enhancement, federatedml, examples

#4224 binning: update anonymous header when migrate from lower version to fate-v1.9.0
  python/federatedml/feature/binning/bin_result.py
  python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
  python/federatedml/transfer_variable/transfer_class/hetero_feature_binning_transfer_variable.py
  python/federatedml/util/anonymous_generator_util.py
Labels: bug

#4220 Feature 1.9.0 sbt selection fix
  python/federatedml/feature/feature_selection/filter_factory.py
Labels: bug

#4221 regenerated pb by grpcio-tools 1.46.3
  python/fate_arch/protobuf/python/basic_meta_pb2.py
  python/fate_arch/protobuf/python/default_empty_fill_pb2.py
  python/fate_arch/protobuf/python/fate_data_structure_pb2.py
  python/fate_arch/protobuf/python/inference_service_pb2.py
  python/fate_arch/protobuf/python/inference_service_pb2_grpc.py
  python/fate_arch/protobuf/python/model_service_pb2.py
  python/fate_arch/protobuf/python/model_service_pb2_grpc.py
  python/fate_arch/protobuf/python/proxy_pb2.py
  python/fate_arch/protobuf/python/proxy_pb2_grpc.py
Labels: arch

#4231 fix homo_binning_transform
  python/federatedml/feature/homo_feature_binning/homo_binning_cpn.py
Labels: bug

#4232 fix homo_binning_transform
  python/federatedml/feature/homo_feature_binning/homo_binning_cpn.py
Labels: bug

#4233 fix pipeline get predict data and fix secureboost example
  examples/pipeline/hetero_sbt/pipeline-hetero-sbt-EINI-with-random-mask.py
  examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary-with-predict.py
  python/fate_client/pipeline/utils/invoker/job_submitter.py
Labels: bug

#4234 fix homo feature binning arbiter model saving
  python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
Labels: bug

#4237 bugfix/1.9.0/homo nn pipeline
  examples/pipeline/homo_nn/__init__.py
  examples/pipeline/homo_nn/_common_component.py
  examples/pipeline/homo_nn/pipeline_homo_nn_multi_label.py
  examples/pipeline/homo_nn/pipeline_homo_nn_multi_layer.py
  examples/pipeline/homo_nn/pipeline_homo_nn_single_layer.py
  examples/pipeline/homo_nn/runner.py
  python/fate_client/pipeline/component/nn/models/sequantial.py
Labels: examples

#4238 fix feature binning examples
  examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-multiclass-multihost-woe.py
  examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-multiclass.py
  examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-bucket-binning.py
  examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-chi-square.py
  examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-gini.py
  examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-iv.py
  examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-ks.py
  examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-quantile-binning.py
Labels: bug, examples

#4239 Feature 1.9.0 anonymou sbt update
  examples/pipeline/hetero_nn/pipeline-hetero-nn-train-binary-recommend-task.py
  python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
  python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
  python/federatedml/protobuf/model_migrate/converter/tree_model_converter.py
  python/federatedml/secureprotol/encrypt.py
  python/federatedml/util/anonymous_generator_util.py
Labels: bug

#4246 fix nn bq
  python/federatedml/nn/hetero_nn/backend/tf_keras/interactive/dense_model.py
Labels: bug

#4241 edit pipeline(#4240)
  python/fate_client/pipeline/backend/pipeline.py
  python/fate_client/pipeline/utils/invoker/job_submitter.py
Labels: enhancement

#4247 edit schema check
  python/federatedml/statistic/scorecard/score_transformer.py
  python/federatedml/unsupervised_learning/kmeans/kmeans_model_base.py
  python/federatedml/util/abnormal_detection.py
Labels: enhancement, federatedml

#4249 Feature 1.9.0 stanadlone fixed
  python/fate_arch/_standalone.py
  python/fate_arch/federation/__init__.py
  python/fate_arch/federation/_federation.py
  python/fate_arch/federation/_gc.py
  python/fate_arch/federation/_type.py
Labels: arch

#4251 fix: fix nn loss fn
  python/federatedml/nn/backend/tf_keras/nn_model.py
Labels: federatedml

#4256 edit unit test
  python/federatedml/feature/binning/test/bucket_binning_test.py
  python/federatedml/feature/binning/test/iv_calculator_test.py
  python/federatedml/feature/binning/test/quantile_binning_test.py
  python/federatedml/feature/feature_scale/test/min_max_scale_test.py
  python/federatedml/feature/feature_scale/test/standard_scale_test.py
  python/federatedml/feature/feature_selection/test/outlier_filter_test.py
  python/federatedml/feature/feature_selection/test/unique_value_filter_test.py
  python/federatedml/feature/feature_selection/test/variance_coe_filter_test.py
  python/federatedml/feature/test/imputer_test.py
  python/federatedml/feature/test/one_hot_test.py
  python/federatedml/feature/test/quantile_test.py
  python/federatedml/statistic/intersect/test/intersection_guest_test.py
  python/federatedml/statistic/intersect/test/intersection_host_test.py
  python/federatedml/statistic/test/hetero_pearson_test.py
  python/federatedml/statistic/test/statistic_cpn_test.py
  python/federatedml/util/test/data_io_test.py
  python/federatedml/util/test/label_transform_test.py
Labels: federatedml

#4265 Feature 1.9.0 rm redundant code
  python/federatedml/feature/feature_selection/iso_model_filter.py
  python/federatedml/util/anonymous_generator.py
Labels: federatedml

#4267 fix ftl float precision
  python/federatedml/transfer_learning/hetero_ftl/ftl_base.py
Labels: bug

#4273 edit examples.experiment_template
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_job_conf.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_job_dsl.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_manually_job_conf.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_manually_job_dsl.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_one_hot_job_conf.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_one_hot_job_dsl.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_pearson_job_conf.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_pearson_job_dsl.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_union_job_conf.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_union_job_dsl.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_verify_job_conf.json
  examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_verify_job_dsl.json
  examples/experiment_template/pipeline/hetero_lr/hetero_lr_testsuite.json
  examples/experiment_template/pipeline/hetero_lr/pipeline_train_lr.py
  examples/experiment_template/pipeline/hetero_lr/pipeline_train_manually_lr.py
  examples/experiment_template/pipeline/hetero_lr/pipeline_train_pearson_lr.py
  examples/experiment_template/pipeline/hetero_lr/pipeline_train_sample_lr.py
  examples/experiment_template/pipeline/hetero_lr/pipeline_train_test_lr.py
  examples/experiment_template/pipeline/hetero_lr/pipeline_train_union_lr.py
  examples/experiment_template/pipeline/hetero_secureboost/hetero_sbt_testsuite.json
  examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_manually_sbt.py
  examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_one_hot_sbt.py
  examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_pearson_sbt.py
  examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_sbt.py
  examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_test_sbt.py
  examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_union_sbt.py
Labels: examples

#4272 edit selection model adapter
  python/federatedml/feature/feature_selection/model_adapter/pearson_adapter.py
Labels: bug, federatedml

#4275 move build
  build/common/get_source_code.md
  build/common/get_source_code.zh.md
  build/common/restore_submodule_github_url.sh
  build/common/update_submodule_from_gitee.sh
  build/package-build/build.md
  build/package-build/build.sh
  build/package-build/build.zh.md
  build/standalone-docker-build/Dockerfile
  build/standalone-docker-build/base/build.sh
  build/standalone-docker-build/base/python/Dockerfile
  build/standalone-docker-build/base/python/init.sh
  build/standalone-docker-build/build.md
  build/standalone-docker-build/build.sh
  build/standalone-docker-build/build.zh.md
  build/standalone-docker-build/docker-entrypoint.sh
  build/standalone-install-build/build.md
  build/standalone-install-build/build.sh
  build/standalone-install-build/build.zh.md
  build/standalone-install-build/init.sh
Labels: arch

#4276 update data_format_preprocess: fix extend columns with match_id
  python/federatedml/util/data_format_preprocess.py
Labels: bug

#4277 add warning for data_transform using without data meta
  doc/federatedml_component/README.md
  doc/federatedml_component/README.zh.md
  doc/federatedml_component/data_transform.md
  python/federatedml/param/data_transform_param.py
  python/federatedml/util/data_transform.py
Labels: federatedml

#4282 add warning in dataio using and modify doc
  doc/api/fate_client/pipeline_component.md
  doc/develop/develop_guide.md
  doc/federatedml_component/union.md
  doc/tutorial/dsl_conf/dsl_conf_tutorial.md
  examples/benchmark_performance/hetero_sbt/test_hetero_secureboost_train_job_conf.json
  examples/benchmark_performance/hetero_sbt/test_hetero_secureboost_train_job_dsl.json
  python/fate_client/pipeline/component/dataio.py
  python/fate_client/pipeline/demo/pipeline-mini-demo.py
  python/fate_client/pipeline/param/dataio_param.py
  python/fate_client/pipeline/test/test_dataio.py
  python/fate_test/fate_test/flow_test/flow_rest_api.py
  python/fate_test/fate_test/flow_test/flow_sdk_api.py
Labels: federatedml, examples

#4281 edit export lr(#3926)
  python/fate_client/pipeline/component/nn/backend/fate_torch/init.py
  python/federatedml/nn/backend/fate_torch/init.py
  python/federatedml/protobuf/model_merge/merge_hetero_lr.py
  python/federatedml/protobuf/model_merge/merge_hetero_models.py
  python/federatedml/protobuf/model_merge/merge_sbt.py
Labels: federatedml

#4283 update cli & sdk
  python/fate_client/flow_client/flow_cli/commands/component.py
  python/fate_client/flow_client/flow_cli/commands/model.py
  python/fate_client/flow_sdk/client/api/component.py
  python/fate_client/flow_sdk/client/api/model.py
  python/fate_test/fate_test/flow_test/flow_cli_api.py
  python/fate_test/fate_test/flow_test/flow_rest_api.py
  python/fate_test/fate_test/flow_test/flow_sdk_api.py
Labels: arch

#4288 add tutorials for uploading data with meta and multiple match id columns
  doc/tutorial/README.md
  doc/tutorial/pipeline/index.md
  doc/tutorial/pipeline/pipeline_tutorial_multiple_id_columns.ipynb
  doc/tutorial/pipeline/pipeline_tutorial_uploading_data_with_meta.ipynb
Labels: document

#4289 Feature 1.9.0 model merge
  doc/tutorial/README.md
  doc/tutorial/model_merge.md
  examples/dsl/v2/hetero_feature_selection/hetero_feature_selection_multiclass_case1_conf.json
  examples/dsl/v2/hetero_feature_selection/hetero_feature_selection_multiclass_case1_dsl.json
  examples/dsl/v2/hetero_feature_selection/hetero_feature_selection_testsuite.json
Labels: federatedml, document, examples

#4292 update release note of fate-v1.9.0
  RELEASE.md
Labels: document

#4286 Feature 1.9 nn suite fix
  doc/tutorial/pipeline/index.md
  doc/tutorial/pipeline/pipeline_tutorial_hetero_nn_torch.ipynb
  examples/benchmark_quality/hetero_nn_pytorch/fate-hetero_nn.py
  examples/benchmark_quality/hetero_nn_pytorch/hetero_nn_breast_config.yaml
  examples/benchmark_quality/hetero_nn_pytorch/hetero_nn_default_credit_config.yaml
  examples/benchmark_quality/hetero_nn_pytorch/hetero_nn_epsilon_5k_config.yaml
  examples/benchmark_quality/hetero_nn_pytorch/hetero_nn_give_credit_config.yaml
  examples/benchmark_quality/hetero_nn_pytorch/hetero_nn_pytorch_benchmark.json
  examples/benchmark_quality/hetero_nn_pytorch/local-hetero_nn.py
  examples/pipeline/hetero_nn/hetero_nn_testsuite.json
Labels: bug

#4299 optim readme
  README.md
  README_zh.md
Labels: document

#4303 update dependency
  fate.env
  python/requirements.txt
Labels: dependencies

#4304 fix typo of RELEASE note
  RELEASE.md
Labels: document
