Repository FederatedAI/FATE, pull requests merged in 2023-11, with the labels that each got.

#5248 recover xentropy computation, align to lgb
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/cross_entropy.py
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/test/cross_entropy_test.py
Labels: bug

#5251 Update Default Key Strength
  python/fate_client/flow_client/flow_cli/commands/test.py
  python/fate_client/pipeline/param/pearson_param.py
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/cross_entropy.py
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/test/cross_entropy_test.py
  python/federatedml/param/encrypt_param.py
  python/federatedml/param/intersect_param.py
  python/federatedml/param/pearson_param.py
  python/federatedml/param/sir_param.py
  python/federatedml/secureprotol/conf/__init__.py
  python/federatedml/secureprotol/diffie_hellman.py
  python/federatedml/secureprotol/encrypt.py
  python/federatedml/secureprotol/fate_paillier.py
  python/federatedml/secureprotol/spdz/spdz.py
  python/federatedml/secureprotol/symmetric_encryption/pohlig_hellman_encryption.py
  python/federatedml/statistic/correlation/hetero_pearson.py
  python/federatedml/statistic/intersect/rsa_intersect/rsa_intersect_base.py
  python/federatedml/util/consts.py
  python/requirements.txt
Labels: enhancement

#5253 Fix predict
  examples/pipeline/homo_nn/pipeline_homo_nn_train_binary.py
  python/federatedml/nn/homo/_init.py
  python/federatedml/nn/homo/client.py
Labels: bug

#5246 add import os in pipeline_tutorial_match_id.ipynb
  doc/tutorial/pipeline/pipeline_tutorial_match_id.ipynb
Labels: bug

#5269 Feature 1.11.5 stats
  examples/pipeline/feature_imputation/README.md
  examples/pipeline/feature_imputation/feature_imputation_testsuite.json
  examples/pipeline/feature_imputation/pipeline-feature-imputation-designated-column.py
  examples/pipeline/union/README.md
  examples/pipeline/union/pipeline-union-axis-1.py
  examples/pipeline/union/union_testsuite.json
  python/fate_client/pipeline/param/feature_imputation_param.py
  python/fate_client/pipeline/param/union_param.py
  python/federatedml/feature/feature_imputation.py
  python/federatedml/feature/imputer.py
  python/federatedml/param/feature_imputation_param.py
  python/federatedml/param/union_param.py
  python/federatedml/statistic/statics.py
  python/federatedml/statistic/union/union.py
  python/federatedml/util/consts.py
Labels: enhancement, federatedml

#5229 dataframe: fix vstack when data types or columns order change
  python/fate/arch/dataframe/ops/_apply_row.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
Labels: bug

#5271 edit feature imputation
  python/federatedml/feature/feature_imputation.py
  python/federatedml/feature/imputer.py
Labels: bug, enhancement, federatedml

#5272 add feature correlation(#5228)
  examples/pipeline/feature_correlation/feature_correlation_testsuite.yaml
  examples/pipeline/feature_correlation/test_feature_correlation.py
  python/fate/arch/utils/trace.py
  python/fate/components/components/__init__.py
  python/fate/components/components/feature_correlation.py
  python/fate/ml/statistics/__init__.py
  python/fate/ml/statistics/pearson_correlation.py
Labels: enhancement, federatedml

#5273 select random mode when counts equal
  python/federatedml/feature/imputer.py
  python/federatedml/statistic/statics.py
Labels: enhancement, federatedml

#5274 add warning if some columns missing mode
  python/federatedml/statistic/statics.py
Labels: enhancement, federatedml

#5275 Feature 2.0.0 rc metrics
  python/fate/ml/feature_binning/hetero_feature_binning.py
Labels: enhancement, federatedml

#5278 edit metrics
  python/fate/ml/feature_selection/hetero_feature_selection.py
Labels: enhancement, federatedml

#5282 edit poisson comments
  python/federatedml/optim/gradient/hetero_poisson_gradient_and_loss.py
Labels: document

#5284 Dev 2.0.0 rc testsuite fix
  examples/benchmark_quality/hetero_secureboost/pipeline_hetero_sbt.py
  examples/benchmark_quality/homo_nn/pipeline_nn_binary.py
  examples/benchmark_quality/homo_nn/pipeline_nn_multi.py
  examples/benchmark_quality/homo_nn/pipeline_nn_regression.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_binary_cv.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_multi.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_regression.py
  examples/pipeline/homo_lr/test_homo_lr_binary.py
  examples/pipeline/homo_nn/test_nn_binary.py
  examples/pipeline/homo_nn/test_nn_multi.py
  examples/pipeline/homo_nn/test_nn_regression.py
Labels: bug

#5301 fix sbt bug
  examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
  python/fate/components/components/hetero_secureboost.py
Labels: bug
