Repository FederatedAI/FATE, pull requests merged in 2023-07, with the labels that each got.

#4966 Dev 2.0.0 beta merge
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/ops/_fillna.py
  python/fate/arch/dataframe/ops/_where.py
  python/fate/arch/dataframe/utils/_dataloader.py
Labels: bug, arch

#4967 dataframe fix: fix cmp between tensor and ndarray/pd.Series
  python/fate/arch/dataframe/ops/_cmp.py
Labels: bug

#4971 edit stat example
  examples/pipeline/test_statistics.py
Labels: federatedml, examples

#4981 Dev 2.0.0 beta debugging
  examples/pipeline/test_lr_sid.py
  examples/pipeline/test_single_linr.py
  python/fate/arch/dataframe/__init__.py
  python/fate/arch/dataframe/ops/_set_item.py
  python/fate/arch/dataframe/utils/__init__.py
  python/fate/arch/dataframe/utils/_dataloader.py
  python/fate/arch/tensor/inside/_op_quantile.py
  python/fate/components/components/coordinated_linr.py
  python/fate/components/core/component_desc/artifacts/metric/_json.py
  python/fate/ml/glm/__init__.py
  python/fate/ml/glm/hetero/__init__.py
  python/fate/ml/glm/hetero/coordinated_linr/__init__.py
  python/fate/ml/glm/hetero/coordinated_linr/arbiter.py
  python/fate/ml/glm/hetero/coordinated_linr/guest.py
  python/fate/ml/glm/hetero/coordinated_linr/host.py
  python/fate/ml/glm/hetero/coordinated_lr/__init__.py
  python/fate/ml/glm/hetero/coordinated_lr/arbiter.py
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
  python/fate/ml/glm/hetero/coordinated_lr/host.py
  python/fate/ml/utils/_optimizer.py
  rust/fate_utils/crates/fate_utils/src/quantile.rs
  rust/fate_utils/python/fate_utils/quantile.pyi
Labels: federatedml

#4983 Dev 2.0.0 beta debugging
  examples/pipeline/test_linr_sid_cv.py
  examples/pipeline/test_lr_sid_cv.py
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_encoder.py
  python/fate/arch/dataframe/ops/_quantile.py
  python/fate/arch/dataframe/utils/_dataloader.py
  python/fate/components/components/__init__.py
  python/fate/components/components/coordinated_linr.py
  python/fate/components/components/coordinated_lr.py
  python/fate/components/components/toy_example.py
  python/fate/components/core/component_desc/_parameter.py
  python/fate/components/core/params/__init__.py
  python/fate/components/core/params/_cv_param.py
  python/fate/ml/glm/hetero/coordinated_linr/guest.py
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
  python/fate/ml/utils/_model_param.py
  python/fate/ml/utils/_optimizer.py
Labels: federatedml, document

#4986 Update predict tools & fix nn bug
  python/fate/components/components/evaluation.py
  python/fate/components/components/nn/nn_runner.py
  python/fate/components/components/nn/runner/default_runner.py
  python/fate/components/components/nn/runner/my_runner.py
  python/fate/components/components/nn/test/test_default_runner.py
  python/fate/ml/glm/homo/lr/client.py
  python/fate/ml/nn/dataset/table.py
  python/fate/ml/utils/predict_tools.py
  python/fate/ml/utils/test/test_predict_format.py
Labels: bug, enhancement

#4985 Dev 2.0.0 beta debugging
  examples/pipeline/test_linr_sid_warm_start.py
  examples/pipeline/test_lr_sid_warm_start.py
  python/fate/arch/_standalone.py
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_encoder.py
  python/fate/arch/dataframe/ops/_histogram.py
  python/fate/arch/protocol/_dh.py
  python/fate/arch/tensor/inside/__init__.py
  python/fate/arch/tensor/inside/_op_hist.py
  python/fate/components/components/coordinated_linr.py
  python/fate/components/components/coordinated_lr.py
  python/fate/ml/aggregator/test/test_fate_utils.py
  python/fate/ml/glm/hetero/coordinated_linr/arbiter.py
  python/fate/ml/glm/hetero/coordinated_linr/guest.py
  python/fate/ml/glm/hetero/coordinated_linr/host.py
  python/fate/ml/glm/hetero/coordinated_lr/arbiter.py
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
  python/fate/ml/glm/hetero/coordinated_lr/host.py
  python/fate/ml/utils/_model_param.py
  python/fate/ml/utils/_optimizer.py
Labels: federatedml

#4989 Dev 2.0.0 beta debugging
  examples/pipeline/test_lr_sid.py
  examples/pipeline/test_single_linr.py
  examples/pipeline/test_single_lr_multi.py
  python/fate/arch/context/_context.py
  python/fate/arch/context/_namespace.py
  python/fate/arch/dataframe/ops/_histogram.py
  python/fate/arch/tensor/inside/_op_hist.py
  python/fate/ml/aggregator/__init__.py
  python/fate/ml/aggregator/base.py
  python/fate/ml/aggregator/plaintext_aggregator.py
  python/fate/ml/aggregator/secure_aggregator.py
  python/fate/ml/aggregator/test/test_aggregator.py
  python/fate/ml/aggregator/test/test_fate_utils.py
  python/fate/ml/glm/homo/lr/test/test_fed_lr.py
  python/fate/ml/glm/homo/lr/test/test_local.py
  python/fate/ml/nn/algo/homo/fedavg.py
  python/fate/ml/nn/dataset/table.py
  python/fate/ml/nn/trainer/test/test_trainer.py
  python/fate/ml/nn/trainer/trainer_base.py
  python/fate/ml/utils/_convergence.py
  python/fate/ml/utils/_optimizer.py
  rust/fate_utils/crates/fate_utils/src/secure_aggregation_helper/mod.rs
Labels: enhancement

#4993 Dev 2.0.0 beta debugging
  python/fate/arch/context/_federation.py
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/arch/dataframe/ops/_encoder.py
  python/fate/arch/dataframe/utils/_sample.py
  python/fate/components/components/__init__.py
  python/fate/components/components/data_split.py
  python/fate/components/components/sample.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
  python/fate/ml/ensemble/learner/decision_tree/test/test_decision_tree.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/splitter.py
  python/fate/ml/ensemble/utils/binning.py
  python/fate/ml/glm/hetero/coordinated_linr/arbiter.py
  python/fate/ml/glm/hetero/coordinated_linr/guest.py
  python/fate/ml/glm/hetero/coordinated_linr/host.py
  python/fate/ml/glm/hetero/coordinated_lr/arbiter.py
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
  python/fate/ml/glm/hetero/coordinated_lr/host.py
  python/fate/ml/glm/homo/lr/client.py
  python/fate/ml/glm/homo/lr/test/test_fed_lr.py
  python/fate/ml/glm/homo/lr/test/test_local.py
  python/fate/ml/model_selection/__init__.py
  python/fate/ml/model_selection/data_split.py
  python/fate/ml/model_selection/sample.py
  python/fate/ml/nn/algo/homo/fedavg.py
  python/fate/ml/utils/_optimizer.py
Labels: federatedml

#4998 optimize glm centralized gradient compute(#4659)
  python/fate/ml/glm/hetero/coordinated_linr/guest.py
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
Labels: enhancement

#4999 Dev 2.0.0 secureboost
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/arch/dataframe/utils/__init__.py
  python/fate/arch/dataframe/utils/_dataloader.py
  python/fate/arch/dataframe/utils/_sample.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
  python/fate/ml/ensemble/learner/decision_tree/test/test_decision_tree.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/loss.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/splitter.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/test/test_loss.py
  python/fate/ml/nn/trainer/test/test_trainer.py
Labels: federatedml

#5002 Feature 2.0.0 sample
  examples/pipeline/test_data_split.py
  examples/pipeline/test_sample.py
  python/fate/components/components/data_split.py
  python/fate/components/components/sample.py
  python/fate/ml/model_selection/data_split.py
  python/fate/ml/model_selection/sample.py
Labels: enhancement

#5004 Feature 2.0.0 sample
  examples/pipeline/test_sample.py
  python/fate/components/components/data_split.py
  python/fate/components/components/sample.py
  python/fate/ml/model_selection/data_split.py
  python/fate/ml/model_selection/sample.py
Labels: federatedml

#5006 dataframe: fix replace op type judgement logic
  python/fate/arch/dataframe/ops/_replace.py
Labels: bug

#5007 raise error when host use woe transform(#4660)
  python/fate/ml/feature_binning/hetero_feature_binning.py
Labels: federatedml

#5009 Feature 2.0.0 sample
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/ml/model_selection/data_split.py
Labels: federatedml

#5010 edit data split(#4779)
  python/fate/components/components/data_split.py
  python/fate/ml/model_selection/data_split.py
Labels: federatedml

#5013 fix data split stratified(#4779)
  examples/pipeline/test_data_split_stratified.py
  python/fate/ml/model_selection/data_split.py
Labels: federatedml

#5016 add param check for 'transform_method'(#4660)
  python/fate/components/components/hetero_feature_binning.py
Labels: federatedml

#5001 add consumed field to artifact
  python/fate/components/core/component_desc/artifacts/_base_type.py
  python/fate/components/core/component_desc/artifacts/data/_dataframe.py
  python/fate/components/core/component_desc/artifacts/data/_directory.py
  python/fate/components/core/component_desc/artifacts/data/_table.py
  python/fate/components/core/component_desc/artifacts/metric/_json.py
  python/fate/components/core/component_desc/artifacts/model/_directory.py
  python/fate/components/core/component_desc/artifacts/model/_json.py
Labels: arch

#5018 Feature 2.0.0 sample
  examples/pipeline/test_sample.py
  python/fate/arch/dataframe/utils/_sample.py
  python/fate/components/components/coordinated_lr.py
  python/fate/components/components/sample.py
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
  python/fate/ml/glm/hetero/coordinated_lr/host.py
  python/fate/ml/model_selection/sample.py
  python/fate/ml/utils/_model_param.py
Labels: federatedml

#5022 rename union & add schema check(#4668)
  examples/pipeline/test_union.py
  python/fate/components/components/__init__.py
  python/fate/components/components/union.py
  python/fate/ml/preprocessing/__init__.py
  python/fate/ml/preprocessing/union.py
Labels: federatedml

#5023 edit schema check(#4668)
  python/fate/ml/preprocessing/union.py
Labels: enhancement, federatedml

#5024 Feature 2.0.0 beta dataframe update
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/arch/dataframe/ops/_indexer.py
  python/fate/arch/dataframe/ops/_promote_types.py
Labels: arch
