Repository FederatedAI/FATE, pull requests merged in 2023-04, with the labels that each got.

#4744 Feature 1.11.0 pellm&bug fix
  doc/tutorial/pipeline/nn_tutorial/GPT2-example.ipynb
  doc/tutorial/pipeline/nn_tutorial/GPT2-multi-task.ipynb
  doc/tutorial/pipeline/nn_tutorial/Homo-NN-Trainer-Interfaces.ipynb
  doc/tutorial/pipeline/nn_tutorial/README.md
  python/fate_client/pipeline/component/__init__.py
  python/fate_client/pipeline/component/hetero_ftl.py
  python/fate_client/pipeline/component/hetero_nn.py
  python/fate_client/pipeline/component/homo_nn.py
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/cross_entropy.py
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/loss.py
  python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/regression_loss.py
  python/federatedml/ensemble/boosting/boosting.py
  python/federatedml/ensemble/boosting/hetero_boosting.py
  python/federatedml/ensemble/boosting/homo_boosting.py
  python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
  python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
  python/federatedml/framework/homo/aggregator/secure_aggregator.py
  python/federatedml/nn/backend/torch/cust.py
  python/federatedml/nn/dataset/base.py
  python/federatedml/nn/dataset/nlp_tokenizer.py
  python/federatedml/nn/homo/client.py
  python/federatedml/nn/homo/trainer/fedavg_trainer.py
  python/federatedml/nn/homo/trainer/trainer_base.py
  python/federatedml/nn/model_zoo/pellm/albert.py
  python/federatedml/nn/model_zoo/pellm/bart.py
  python/federatedml/nn/model_zoo/pellm/bert.py
  python/federatedml/nn/model_zoo/pellm/deberta.py
  python/federatedml/nn/model_zoo/pellm/distillbert.py
  python/federatedml/nn/model_zoo/pellm/gpt2.py
  python/federatedml/nn/model_zoo/pellm/parameter_efficient_llm.py
  python/federatedml/nn/model_zoo/pellm/roberta.py
  python/federatedml/protobuf/generated/homo_nn_model_param_pb2.py
  python/federatedml/protobuf/proto/homo-nn-model-param.proto
  python/requirements.txt
Labels: federatedml

#4748 fix doc bug
  doc/tutorial/pipeline/nn_tutorial/Homo-NN-Customize-Trainer.ipynb
Labels: document

#4750 update requirement
  python/requirements.txt
Labels: federatedml

#4752 remove redundant code
  python/federatedml/nn/homo/client.py
  python/federatedml/nn/model_zoo/pellm/parameter_efficient_llm.py
Labels: bug

#4757 update release note of fate-v1.11
  RELEASE.md
Labels: document

#4758 update release note of fate-v1.11.0
  RELEASE.md
Labels: document

#4762 update bert doc
  doc/tutorial/pipeline/nn_tutorial/Bert-example.ipynb
Labels: document

#4782 fix RELEASE doc
  RELEASE.md
Labels: document

#4806 Feature 1.11.1 graph bug fix
  doc/tutorial/pipeline/nn_tutorial/Homo-Graph.ipynb
  doc/tutorial/pipeline/nn_tutorial/README.md
  python/federatedml/nn/homo/trainer/fedavg_graph_trainer.py
Labels: bug, federatedml

#4808 Feature 1.11.1 doc update
  doc/tutorial/pipeline/nn_tutorial/GPT2-example.ipynb
  doc/tutorial/pipeline/nn_tutorial/GPT2-multi-task.ipynb
Labels: federatedml, document

#4809 update examples and doc
  README.md
  README_zh.md
  doc/federatedml_component/intersect.md
  doc/tutorial/README.zh.md
  doc/tutorial/fate_llm/GPT2-example.ipynb
  doc/tutorial/fate_llm/GPT2-multi-task.ipynb
  doc/tutorial/fate_llm/README.md
  doc/tutorial/pipeline/nn_tutorial/README.md
  examples/dsl/v2/intersect/README.md
  examples/dsl/v2/intersect/intersect_testsuite.json
  examples/dsl/v2/intersect/test_intersect_job_raw_conf.json
  examples/dsl/v2/intersect/test_intersect_job_raw_multi_host_conf.json
  examples/dsl/v2/intersect/test_intersect_job_raw_sm3_conf.json
  examples/pipeline/intersect/README.md
  examples/pipeline/intersect/intersect_testsuite.json
  examples/pipeline/intersect/pipeline-intersect-multi-raw.py
  examples/pipeline/intersect/pipeline-intersect-raw-sm3.py
  examples/pipeline/intersect/pipeline-intersect-raw.py
  examples/pipeline/intersect/pipeline-intersect-with-union.py
  python/federatedml/param/intersect_param.py
Labels: document

#4810 update doc of guidelines
  doc/tutorial/fate_llm/GPT2-example.ipynb
  doc/tutorial/fate_llm/GPT2-multi-task.ipynb
Labels: document

#4813 fix import when geometric is not installed
  python/federatedml/nn/dataset/graph.py
Labels: bug

#4812 Update documents
  README.md
  README_zh.md
  doc/federatedml_component/intersect.md
  doc/tutorial/README.zh.md
  doc/tutorial/fate_llm/GPT2-example.ipynb
  doc/tutorial/fate_llm/GPT2-multi-task.ipynb
  doc/tutorial/fate_llm/README.md
  doc/tutorial/pipeline/nn_tutorial/README.md
  examples/dsl/v2/intersect/README.md
  examples/dsl/v2/intersect/intersect_testsuite.json
  examples/dsl/v2/intersect/test_intersect_job_raw_conf.json
  examples/dsl/v2/intersect/test_intersect_job_raw_multi_host_conf.json
  examples/dsl/v2/intersect/test_intersect_job_raw_sm3_conf.json
  examples/pipeline/intersect/README.md
  examples/pipeline/intersect/intersect_testsuite.json
  examples/pipeline/intersect/pipeline-intersect-multi-raw.py
  examples/pipeline/intersect/pipeline-intersect-raw-sm3.py
  examples/pipeline/intersect/pipeline-intersect-raw.py
  examples/pipeline/intersect/pipeline-intersect-with-union.py
  python/federatedml/nn/dataset/graph.py
  python/federatedml/param/intersect_param.py
Labels: document, examples

#4822 (github): purge slash-command-dispatch
  .github/workflows/autopep8-command.yml
  .github/workflows/fate-test-command.yml
  .github/workflows/slash-command-dispatch.yml
Labels: CI

#4831 fix padding
  doc/tutorial/fate_llm/GPT2-multi-task.ipynb
Labels: document
