Repository FederatedAI/FATE, pull requests merged in 2023-09, with the labels that each got.

#5110 optimizer secureboost
  python/fate/arch/dataframe/ops/_set_item.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
Labels: enhancement

#5112 dev 2.0.0 beta build pypi
  python/fate/_info.py
  python/fate/arch/_standalone.py
  python/fate/arch/computing/standalone/_csession.py
  python/fate/arch/dataframe/ops/_apply_row.py
  python/fate/components/core/_load_computing.py
  python/fate/components/core/essential/_artifact_type.py
  python/fate/components/core/spec/logger.py
  python/fate/components/entrypoint/cli/component/execute_cli.py
  python/fate/components/entrypoint/cli/test/execute.py
  python/fate/components/entrypoint/utils.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
  python/requirements-fate.txt
  python/requirements-pulsar.txt
  python/setup.py
Labels: arch

#5114 change doc
  java/osx/RELEASE.md
Labels: federation

#5115 optimizer secureboost predicting,and apply_row api in dataframe
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_apply_row.py
  python/fate/arch/dataframe/ops/_set_item.py
  python/fate/ml/ensemble/algo/secureboost/common/predict.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
Labels: arch

#5117 coordinated lr & linr add key length & floating point precision param…
  examples/pipeline/coordinated_linr/test_linr.py
  examples/pipeline/coordinated_linr/test_linr_multi_host.py
  examples/pipeline/multi_model/test_multi.py
  python/fate/arch/tensor/distributed/_ops_others.py
  python/fate/components/components/coordinated_linr.py
  python/fate/components/components/coordinated_lr.py
  python/fate/components/components/hetero_feature_binning.py
  python/fate/ml/feature_binning/hetero_feature_binning.py
  python/fate/ml/glm/hetero/coordinated_linr/arbiter.py
  python/fate/ml/glm/hetero/coordinated_linr/guest.py
  python/fate/ml/glm/hetero/coordinated_linr/host.py
  python/fate/ml/glm/hetero/coordinated_lr/arbiter.py
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
  python/fate/ml/glm/hetero/coordinated_lr/host.py
  python/fate/ml/utils/_optimizer.py
  python/fate/ml/utils/predict_tools.py
  python/fate_test/fate_test/_config.py
Labels: federatedml, examples

#5118 Fix log
  python/federatedml/nn/homo/trainer/fedavg_trainer.py
Labels: bug

#5120 dataframe: support histogram stat without passing node positions
  python/fate/arch/dataframe/_dataframe.py
Labels: arch

#5122 Update requirement
  python/requirements-fate-llm.txt
Labels: enhancement

#5124 coordinated lr & linr use he param for he kind and key length (#4659)
  python/fate/arch/dataframe/_dataframe.py
  python/fate/components/components/coordinated_linr.py
  python/fate/components/components/coordinated_lr.py
  python/fate/components/core/params/__init__.py
  python/fate/components/core/params/_he_param.py
  python/fate/ml/glm/hetero/coordinated_linr/arbiter.py
  python/fate/ml/glm/hetero/coordinated_linr/guest.py
  python/fate/ml/glm/hetero/coordinated_linr/host.py
  python/fate/ml/glm/hetero/coordinated_lr/arbiter.py
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
  python/fate/ml/glm/hetero/coordinated_lr/host.py
Labels: federatedml

#5127 type promote only when both tensor are torch.Tensor
  python/fate/arch/tensor/distributed/_op_matmul.py
Labels: enhancement, arch

#5128 dataframe: fix getitem attr order
  python/fate/arch/dataframe/manager/schema_manager.py
Labels: bug

#5129 fix convert block warning
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/ops/_encoder.py
  python/fate/arch/dataframe/utils/_sample.py
  python/fate/ml/model_selection/data_split.py
Labels: arch

#5130 dataframe: fix row indexing by label/weight
  python/fate/arch/dataframe/ops/_dimension_scaling.py
Labels: bug

#5131 dataframe: clean redundant code
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/_frame_reader.py
  python/fate/arch/dataframe/io/_json_serialization.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/arch/dataframe/ops/_indexer.py
  python/fate/arch/dataframe/ops/_isin.py
  python/fate/arch/dataframe/storage/__init__.py
  python/fate/arch/dataframe/storage/_match_index.py
  python/fate/arch/dataframe/storage/_sample_index.py
  python/fate/arch/dataframe/storage/_value_store.py
Labels: arch

#5132 Feature 2.0.0 beta fate test
  python/fate/arch/histogram/values/_cipher.py
  python/fate/arch/histogram/values/_values.py
  python/fate/components/components/hetero_feature_binning.py
  python/fate/ml/feature_binning/hetero_feature_binning.py
Labels: federatedml

#5133 doc update
  doc/federatedml_component/README.md
  doc/federatedml_component/README.zh.md
Labels: document

#5137 Feature 2.0.0 beta fate test
  examples/benchmark_quality/lr/pipeline-lr-binary.py
  python/fate/components/core/params/_he_param.py
  python/fate/ml/feature_binning/hetero_feature_binning.py
Labels: bug

#5135 dataframe: support rename same column
  python/fate/arch/dataframe/manager/schema_manager.py
Labels: arch

#5151 Feature 2.0.0 beta fate test
  doc/tutorial/fate_test_tutorial.md
  python/fate/ml/feature_binning/hetero_feature_binning.py
  python/fate/ml/feature_selection/hetero_feature_selection.py
  python/fate_test/__init__.py
  python/fate_test/fate_test/__init__.py
  python/fate_test/fate_test/_ascii.py
  python/fate_test/fate_test/_client.py
  python/fate_test/fate_test/_config.py
  python/fate_test/fate_test/_flow_client.py
  python/fate_test/fate_test/_io.py
  python/fate_test/fate_test/_parser.py
  python/fate_test/fate_test/scripts/__init__.py
  python/fate_test/fate_test/scripts/_options.py
  python/fate_test/fate_test/scripts/_utils.py
  python/fate_test/fate_test/scripts/benchmark_cli.py
  python/fate_test/fate_test/scripts/cli.py
  python/fate_test/fate_test/scripts/config_cli.py
  python/fate_test/fate_test/scripts/data_cli.py
  python/fate_test/fate_test/scripts/generate_mock_data.py
  python/fate_test/fate_test/scripts/performance_cli.py
  python/fate_test/fate_test/scripts/testsuite_cli.py
  python/fate_test/fate_test/utils.py
  python/fate_test/pyproject.toml
  python/fate_test/setup.py
  python/requirements-fate-test.txt
Labels: enhancement

#5148 update requirements of fate
  python/requirements-fate.txt
Labels: document

#5152 dataframe: adjust for anonymous sitename
  python/fate/arch/dataframe/_frame_reader.py
  python/fate/arch/dataframe/io/_json_serialization.py
  python/fate/arch/dataframe/manager/data_manager.py
  python/fate/arch/dataframe/manager/schema_manager.py
  python/fate/arch/dataframe/manager/utils/_anonymous_generator.py
  python/fate/components/components/dataframe_transformer.py
Labels: arch

#5153 fix percentile filter selection(#4661)
  python/fate/components/core/params/_filter_param.py
  python/fate/ml/feature_selection/hetero_feature_selection.py
Labels: enhancement

#5155 dataframe: fix apply_row type judging
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/ops/_apply_row.py
Labels: bug

#5157 dataframe: fix column indexing order problem
  python/fate/arch/dataframe/manager/block_manager.py
Labels: bug

#5158 edit pipeline examples
  examples/pipeline/data_split/test_data_split_stratified.py
Labels: examples

#5160 update requirements
  python/requirements-fate.txt
  python/setup.py
Labels: document

#5159 edit pipeline example
  examples/pipeline/data_split/test_data_split_stratified.py
Labels: examples

#5165 Feature 2.0.0 beta fate test
  examples/pipeline/hetero_feature_binning/test_feature_binning_asymmetric.py
  examples/pipeline/hetero_feature_binning/test_feature_binning_quantile.py
  python/fate/components/components/hetero_feature_binning.py
Labels: federatedml

#5168 add random state to lr bq example
  examples/benchmark_quality/lr/vehicle_config.yaml
  python/requirements-fate.txt
  python/setup.py
Labels: enhancement, examples

#5170 dataframe: add dtypes
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/manager/data_manager.py
Labels: arch

#5172 fix binning when he kind is mock(#4660)
  python/fate/arch/histogram/values/_encoded.py
  python/fate/ml/feature_binning/hetero_feature_binning.py
Labels: federatedml

#5173 dataframe: fix bucketize when boudaries are all integers
  python/fate/arch/dataframe/ops/_encoder.py
Labels: bug

#5175 secureboost: hist fix, use dtypes from gh frame
  python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
Labels: federatedml

#5176 Dev 2.0.0 benchmark verify
  examples/benchmark_quality/hetero_sbt/hetero_sbt_benchmark.yaml
  examples/benchmark_quality/hetero_sbt/pipeline_hetero_sbt.py
Labels: document

#5177 remove logs
  python/fate/ml/ensemble/algo/secureboost/test/test_hetero_sbt_binary.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/splitter.py
Labels: federatedml

#5178 udpate quick start doc for component using
  doc/2.0/quick_start.md
Labels: document

#5179 mv fate components document
  doc/2.0/README.md
  doc/2.0/fate/components/README.md
  doc/2.0/fate/components/README.zh.md
  doc/2.0/fate/components/data_split.md
  doc/2.0/fate/components/feature_binning.md
  doc/2.0/fate/components/feature_scale.md
  doc/2.0/fate/components/feature_selection.md
  doc/2.0/fate/components/linear_regression.md
  doc/2.0/fate/components/logistic_regression.md
  doc/2.0/fate/components/psi.md
  doc/2.0/fate/components/sample.md
  doc/2.0/fate/components/statistics.md
  doc/2.0/fate/components/union.md
Labels: document

#5181 update release of 2.0.0-beta
  RELEASE.md
Labels: document

#5183 Dev 2.0.0 nn sbt doc
  doc/2.0/fate/ml/hetero_sbt_tutorial.ipynb
  doc/2.0/fate/ml/homo_nn_tutorial.ipynb
Labels: document

#5184 update release
  RELEASE.md
Labels: document

#5185 update torch to cpu for manually deploy
  python/requirements-fate.txt
Labels: document

#5186 Fix doc: rename, fix data bug, add sbt/nn/lr pipeline examples
  doc/2.0/fate/ml/hetero_secureboost_tutorial.ipynb
  examples/benchmark_quality/hetero_secureboost/hetero_sbt_benchmark.yaml
  examples/benchmark_quality/hetero_secureboost/pipeline_hetero_sbt.py
  examples/benchmark_quality/hetero_secureboost/sbt_breast_config.yaml
  examples/benchmark_quality/hetero_secureboost/sbt_default_credit_config.yaml
  examples/benchmark_quality/hetero_secureboost/sbt_student_config.yaml
  examples/benchmark_quality/hetero_secureboost/xgb.py
  examples/benchmark_quality/hetero_secureboost/xgb_breast_config.yaml
  examples/benchmark_quality/hetero_secureboost/xgb_default_credit_config.yaml
  examples/benchmark_quality/hetero_secureboost/xgb_student_config.yaml
  examples/benchmark_quality/homo_nn/homo_nn_benchmark.yaml
  examples/pipeline/hetero_secureboost/hetero_secureboost_testsuite.yaml
  examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_regression.py
  examples/pipeline/homo_lr/homo_lr_testsuite.yaml
  examples/pipeline/homo_lr/test_homo_lr_binary.py
  examples/pipeline/homo_nn/homo_nn_testsuite.yaml
  examples/pipeline/homo_nn/test_nn_binary.py
  examples/pipeline/homo_nn/test_nn_multi.py
  examples/pipeline/homo_nn/test_nn_regression.py
Labels: document

#5187 Feature 2.0.0 quick guide update
  README.md
  README_zh.md
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/README.zh.md
  doc/2.0/quick_start.md
  schemas/components/feature_scale.yaml
  schemas/components/intersection.yaml
  schemas/components/lr.yaml
  schemas/components/reader.yaml
  schemas/jobs/training_dag.yaml
Labels: document

#5189 fix statistic filter param(#4661)
  python/fate/components/core/params/_filter_param.py
Labels: federatedml

#5191 edit doc
  doc/api/fate_test.md
Labels: document

#5193 update sklearn requirements
  python/requirements-fate.txt
  python/setup.py
Labels: document

#5194 update release note
  RELEASE.md
Labels: document

#5195 doc: update zh doc of standalone-deploy
  deploy/standalone-deploy/README.zh.md
Labels: document

#5196 fix standalone deploy zh doc
  deploy/standalone-deploy/README.zh.md
Labels: document

#5197 update doc
  doc/2.0/fate/ml/hetero_secureboost_tutorial.ipynb
  doc/2.0/fate/ml/homo_nn_tutorial.ipynb
Labels: document

#5200 update readme, add fate_test link
  README.md
  README_zh.md
  doc/images/FATE_logo.png
Labels: document

#5204 Feature 2.0.0 quick guide update
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/README.zh.md
  doc/2.0/quick_start.md
Labels: document

#5205 Update deployment document
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/README.zh.md
  doc/2.0/quick_start.md
Labels: document

#5207 dataframe: fix onehot to support higher version of sklearn
  python/fate/arch/dataframe/ops/_encoder.py
  python/requirements-fate.txt
  python/setup.py
Labels: arch

#5206 update fate_client requirements
  python/fate_client/pyproject.toml
  python/fate_client/setup.py
Labels: deploy

#5208 optim bug for osx and pulsar maxsize
  python/fate/arch/federation/osx/_federation.py
  python/fate/arch/federation/pulsar/_federation.py
Labels: bug, arch
