Repository FederatedAI/FATE, pull requests merged in 2023-06, with the labels that each got.

#4888 Fix secure agg
  python/federatedml/nn/homo/trainer/fedavg_trainer.py
Labels: bug, enhancement, federatedml

#4900 update dataframe: support skew/kurt/power
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_stat.py
Labels: enhancement

#4905 dataframe interface update
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_missing.py
  python/fate/arch/dataframe/ops/_stat.py
Labels: enhancement

#4906 update dataframe: add describe
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_stat.py
Labels: enhancement

#4913 dataframe api update
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/manager/data_manager.py
  python/fate/arch/dataframe/manager/schema_manager.py
  python/fate/arch/dataframe/ops/_encoder.py
Labels: arch

#4917 add scale with minmax & standard method (#4670)
  examples/pipeline/test_feature_scale.py
  python/fate/components/components/feature_scale.py
  python/fate/ml/feature_scale/feature_scale.py
  python/fate/ml/preprocessing/__init__.py
  python/fate/ml/preprocessing/feature_scale.py
Labels: enhancement, federatedml

#4924 Feature 2.0.0 beta dataframe update
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/_frame_reader.py
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/manager/data_manager.py
  python/fate/arch/dataframe/manager/schema_manager.py
  python/fate/arch/dataframe/ops/_field_extract.py
  python/fate/arch/dataframe/ops/_indexer.py
  python/fate/arch/dataframe/ops/_set_item.py
  python/fate/arch/dataframe/ops/_transformer.py
Labels: bug

#4946 Dev 2.0.0 beta merge
  python/fate/arch/context/_context.py
  python/fate/arch/context/_metrics.py
  python/fate/arch/context/_namespace.py
  python/fate/arch/context/metric/_handler.py
  python/fate/arch/context/metric/_incomplte_metrics.py
  python/fate/arch/context/metric/_metric.py
  python/fate/arch/context/metric/_metrics.py
  python/fate/arch/context/metric/_type.py
  python/fate/arch/context/metric/_wrap.py
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/io/_json_serialization.py
  python/fate/arch/dataframe/ops/_data_overview.py
  python/fate/arch/dataframe/ops/_transformer.py
  python/fate/components/components/__init__.py
  python/fate/components/components/dataframe_io_test.py
  python/fate/components/components/demo.py
  python/fate/components/core/component_desc/_component_io.py
  python/fate/components/core/component_desc/artifacts/_base_type.py
  python/fate/components/core/component_desc/artifacts/data/_dataframe.py
  python/fate/components/core/component_desc/artifacts/data/_directory.py
  python/fate/components/core/component_desc/artifacts/data/_table.py
  python/fate/components/core/component_desc/artifacts/metric/_json.py
  python/fate/components/core/component_desc/artifacts/model/_directory.py
  python/fate/components/core/component_desc/artifacts/model/_json.py
  python/fate/interface/__init__.py
  python/fate/interface/_consts.py
  python/fate/interface/_metric.py
  python/fate/interface/_party.py
Labels: arch

#4950 dev 2.0.0 beta merge
  python/fate/arch/_standalone.py
  python/fate/arch/abc/__init__.py
  python/fate/arch/abc/_federation.py
  python/fate/arch/abc/_party.py
  python/fate/arch/abc/_table.py
  python/fate/arch/computing/__init__.py
  python/fate/arch/computing/eggroll/_csession.py
  python/fate/arch/computing/eggroll/_table.py
  python/fate/arch/computing/spark/_csession.py
  python/fate/arch/computing/spark/_table.py
  python/fate/arch/computing/standalone/_csession.py
  python/fate/arch/computing/standalone/_table.py
  python/fate/arch/context/_cipher.py
  python/fate/arch/context/_context.py
  python/fate/arch/context/_federation.py
  python/fate/arch/context/_metrics.py
  python/fate/arch/context/_namespace.py
  python/fate/arch/federation/_federation.py
  python/fate/arch/federation/_gc.py
  python/fate/arch/federation/eggroll/_federation.py
  python/fate/arch/federation/osx/_federation.py
  python/fate/arch/federation/pulsar/_federation.py
  python/fate/arch/federation/rabbitmq/_federation.py
  python/fate/arch/federation/standalone/_federation.py
  python/fate/components/components/demo.py
  python/fate/components/components/evaluation.py
  python/fate/components/components/hetero_lr.py
  python/fate/components/components/multi_model_test.py
  python/fate/components/core/__init__.py
  python/fate/components/core/_cpn_reexport.py
  python/fate/components/core/_load_metric_handler.py
  python/fate/components/core/component_desc/_component.py
  python/fate/components/core/component_desc/_component_artifact.py
  python/fate/components/core/component_desc/_component_io.py
  python/fate/components/core/component_desc/_metric.py
  python/fate/components/core/component_desc/_parameter.py
  python/fate/components/core/component_desc/artifacts/metric/__init__.py
  python/fate/components/core/component_desc/artifacts/metric/_json.py
  python/fate/components/core/component_desc/artifacts/model/__init__.py
  python/fate/components/core/loader/metric.py
  python/fate/components/core/params/_fields.py
  python/fate/components/core/spec/component.py
  python/fate/components/entrypoint/component.py
  python/fate/interface/__init__.py
  python/fate/interface/_address.py
  python/fate/interface/_cipher.py
  python/fate/interface/_computing.py
  python/fate/interface/_data_io.py
  python/fate/interface/_gc.py
Labels: arch

#4956 fix intersection io
  python/fate/components/components/intersection.py
Labels: federatedml

#4959 dataframe: fix when df.label = ... cause type promoting
  python/fate/arch/dataframe/ops/_set_item.py
Labels: bug
