Repository FederatedAI/FATE, pull requests merged in 2023-12, with the labels that each got.

#5303 Fix example
  examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
Labels: bug

#5309 Feature 2.0.0 rc sshe glm
  examples/pipeline/sshe_linr/sshe_linr_testsuite.yaml
  examples/pipeline/sshe_linr/test_linr.py
  examples/pipeline/sshe_linr/test_linr_cv.py
  examples/pipeline/sshe_linr/test_linr_warm_start.py
  examples/pipeline/sshe_lr/sshe_lr_testsuite.yaml
  examples/pipeline/sshe_lr/test_lr.py
  examples/pipeline/sshe_lr/test_lr_cv.py
  examples/pipeline/sshe_lr/test_lr_multi_class.py
  examples/pipeline/sshe_lr/test_lr_predict_w_torch.py
  examples/pipeline/sshe_lr/test_lr_validate.py
  examples/pipeline/sshe_lr/test_lr_warm_start.py
  launchers/sshe_linr_launcher.py
  launchers/sshe_lr_launcher.py
  python/fate/arch/protocol/mpc/mpc.py
  python/fate/arch/protocol/mpc/nn/sshe/linr_layer.py
  python/fate/arch/protocol/mpc/nn/sshe/lr_layer.py
  python/fate/arch/protocol/mpc/primitives/arithmetic.py
  python/fate/components/components/__init__.py
  python/fate/components/components/sshe_linr.py
  python/fate/components/components/sshe_lr.py
  python/fate/ml/glm/hetero/sshe/__init__.py
  python/fate/ml/glm/hetero/sshe/sshe_linr.py
  python/fate/ml/glm/hetero/sshe/sshe_lr.py
  python/fate/ml/mpc/sshe_linr.py
  python/fate/ml/mpc/sshe_lr.py
  python/fate/ml/utils/_convergence.py
  python/fate/ml/utils/_model_param.py
Labels: enhancement, federatedml

#5318 edit examples(#5227)
  examples/benchmark_quality/linr/hetero_linr_benchmark.yaml
  examples/benchmark_quality/linr/linr_config.yaml
  examples/pipeline/sshe_linr/sshe_linr_testsuite.yaml
  examples/pipeline/sshe_linr/test_linr_validate.py
Labels: examples

#5322 update examples/pipeline
  examples/pipeline/config.yaml
  examples/pipeline/coordinated_linr/test_linr.py
  examples/pipeline/coordinated_linr/test_linr_cv.py
  examples/pipeline/coordinated_linr/test_linr_multi_host.py
  examples/pipeline/coordinated_linr/test_linr_warm_start.py
  examples/pipeline/coordinated_lr/test_lr.py
  examples/pipeline/coordinated_lr/test_lr_cv.py
  examples/pipeline/coordinated_lr/test_lr_multi_class.py
  examples/pipeline/coordinated_lr/test_lr_multi_host.py
  examples/pipeline/coordinated_lr/test_lr_predict_w_torch.py
  examples/pipeline/coordinated_lr/test_lr_validate.py
  examples/pipeline/coordinated_lr/test_lr_warm_start.py
  examples/pipeline/data_split/test_data_split.py
  examples/pipeline/data_split/test_data_split_multi_host.py
  examples/pipeline/data_split/test_data_split_stratified.py
  examples/pipeline/feature_correlation/test_feature_correlation.py
  examples/pipeline/feature_scale/test_scale_min_max.py
  examples/pipeline/feature_scale/test_scale_standard.py
  examples/pipeline/feature_scale/test_scale_w_lr.py
  examples/pipeline/hetero_feature_binning/test_feature_binning_asymmetric.py
  examples/pipeline/hetero_feature_binning/test_feature_binning_bucket.py
  examples/pipeline/hetero_feature_binning/test_feature_binning_multi_host.py
  examples/pipeline/hetero_feature_binning/test_feature_binning_quantile.py
  examples/pipeline/hetero_feature_selection/test_feature_selection_binning.py
  examples/pipeline/hetero_feature_selection/test_feature_selection_manual.py
  examples/pipeline/hetero_feature_selection/test_feature_selection_multi_host.py
  examples/pipeline/hetero_feature_selection/test_feature_selection_multi_model.py
  examples/pipeline/hetero_feature_selection/test_feature_selection_statistics.py
  examples/pipeline/hetero_nn/test_nn_binary.py
  examples/pipeline/hetero_nn/test_nn_binary_with_fedpass.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_binary_cv.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_multi.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_regression.py
  examples/pipeline/homo_lr/test_homo_lr_binary.py
  examples/pipeline/homo_lr/test_homo_lr_multi_ovr.py
  examples/pipeline/homo_nn/test_nn_binary.py
  examples/pipeline/homo_nn/test_nn_multi.py
  examples/pipeline/homo_nn/test_nn_regression.py
  examples/pipeline/multi_model/test_multi.py
  examples/pipeline/multi_model/test_multi_preprocessing.py
  examples/pipeline/multi_model/test_multi_w_predict.py
  examples/pipeline/sample/test_sample.py
  examples/pipeline/sample/test_sample_multi_host.py
  examples/pipeline/sample/test_sample_unilateral.py
  examples/pipeline/sshe_linr/test_linr.py
  examples/pipeline/sshe_linr/test_linr_cv.py
  examples/pipeline/sshe_linr/test_linr_validate.py
  examples/pipeline/sshe_linr/test_linr_warm_start.py
  examples/pipeline/sshe_lr/test_lr.py
  examples/pipeline/sshe_lr/test_lr_cv.py
  examples/pipeline/sshe_lr/test_lr_multi_class.py
  examples/pipeline/sshe_lr/test_lr_predict_w_torch.py
  examples/pipeline/sshe_lr/test_lr_validate.py
  examples/pipeline/sshe_lr/test_lr_warm_start.py
  examples/pipeline/statistics/test_statistics.py
  examples/pipeline/statistics/test_statistics_default.py
  examples/pipeline/union/test_union.py
  python/fate/components/components/reader.py
Labels: examples

#5327 merge rc-new
  doc/2.0/osx/bfia-x.proto
  doc/2.0/osx/bfia-y.proto
  doc/2.0/osx/osx-tls.md
  doc/2.0/osx/osx.md
  java/osx/bin/service.sh
  java/osx/osx-broker/pom.xml
  java/osx/osx-broker/src/main/java/org/fedai/osx/broker/Bootstrap.java
  java/osx/osx-broker/src/main/java/org/fedai/osx/broker/eggroll/PutBatchSinkPushRespSO.java
  java/osx/osx-broker/src/main/java/org/fedai/osx/broker/grpc/QueuePushReqStreamObserver.java
  java/osx/osx-broker/src/main/java/org/fedai/osx/broker/http/HttpsClientPool.java
  java/osx/osx-broker/src/main/java/org/fedai/osx/broker/provider/FateTechProvider.java
  java/osx/osx-broker/src/main/java/org/fedai/osx/broker/router/DefaultFateRouterServiceImpl.java
  java/osx/osx-broker/src/main/java/org/fedai/osx/broker/router/RouterTableAddService.java
  java/osx/osx-broker/src/main/java/org/fedai/osx/broker/server/OsxServer.java
  java/osx/osx-broker/src/main/resources/broker/broker.properties
  java/osx/osx-broker/src/test/resources/cert4test/ca.crt
  java/osx/osx-broker/src/test/resources/cert4test/ca.key
  java/osx/osx-broker/src/test/resources/cert4test/client.crt
  java/osx/osx-broker/src/test/resources/cert4test/client.csr
  java/osx/osx-broker/src/test/resources/cert4test/client.key
  java/osx/osx-broker/src/test/resources/cert4test/client.pem
  java/osx/osx-broker/src/test/resources/cert4test/server.crt
  java/osx/osx-broker/src/test/resources/cert4test/server.csr
  java/osx/osx-broker/src/test/resources/cert4test/server.key
  java/osx/osx-broker/src/test/resources/cert4test/server.pem
  java/osx/osx-broker/src/test/resources/keystore/client/client.cer
  java/osx/osx-broker/src/test/resources/keystore/client/identity.jks
  java/osx/osx-broker/src/test/resources/keystore/client/truststore.jks
  java/osx/osx-broker/src/test/resources/keystore/server/identity.jks
  java/osx/osx-broker/src/test/resources/keystore/server/server.cer
  java/osx/osx-broker/src/test/resources/keystore/server/truststore.jks
  java/osx/osx-core/pom.xml
  java/osx/osx-core/src/main/java/org/fedai/osx/core/config/MetaInfo.java
  java/osx/osx-core/src/main/java/org/fedai/osx/core/constant/Dict.java
  java/osx/osx-core/src/main/java/org/fedai/osx/core/router/RouterInfo.java
  java/osx/osx-core/src/main/java/org/fedai/osx/core/utils/OSXCertUtils.java
  java/osx/osx-core/src/main/java/org/fedai/osx/core/utils/OsxX509TrustManager.java
  java/osx/pom.xml
Labels: federation

#5330 SSHE LR & LinR record train data header
  python/fate/ml/glm/hetero/sshe/sshe_linr.py
  python/fate/ml/glm/hetero/sshe/sshe_lr.py
Labels: federatedml

#5334 edit logging
  python/fate/ml/glm/hetero/sshe/sshe_linr.py
  python/fate/ml/glm/hetero/sshe/sshe_lr.py
Labels: enhancement

#5336 Remove redundant code for osx
  python/fate/arch/federation/backends/osx/_federation.py
  python/fate/arch/federation/backends/osx/_mq_channel.py
  python/fate/arch/federation/backends/rabbitmq/_federation.py
  python/fate/arch/federation/message_queue/_federation.py
Labels: arch

#5341 edit examples
  examples/pipeline/coordinated_lr/test_lr_multi_class.py
  examples/pipeline/hetero_feature_binning/test_feature_binning_quantile.py
Labels: examples

#5343 edit examples
  examples/pipeline/hetero_feature_selection/test_feature_selection_binning.py
Labels: examples

#5344 homo_nn: deepspeed support
  python/fate/components/components/nn/runner/homo_default_runner.py
  python/fate/ml/aggregator/__init__.py
  python/fate/ml/aggregator/aggregator_wrapper.py
  python/fate/ml/nn/homo/fedavg.py
  python/fate/ml/nn/trainer/trainer_base.py
Labels: federatedml

#5348 update reqs
  python/requirements-pulsar.txt
Labels: dependencies

#5353 edit data split examples
  examples/pipeline/data_split/data_split_testsuite.yaml
  examples/pipeline/data_split/test_data_split_stratified_homo.py
Labels: examples

#5359 fix sshe loss
  python/fate/ml/glm/hetero/sshe/sshe_linr.py
  python/fate/ml/glm/hetero/sshe/sshe_lr.py
Labels: enhancement, federatedml

#5360 Signed-off-by: weijingchen <talkingwallace@sohu.com>
  examples/pipeline/hetero_secureboost/test_hetero_sbt_binary_warm_start.py
  python/fate/ml/ensemble/algo/secureboost/hetero/_base.py
  python/fate/ml/ensemble/algo/secureboost/hetero/guest.py
Labels: bug

#5363 Dev 2.0.0 rc final round fix
  python/fate/ml/ensemble/algo/secureboost/hetero/guest.py
Labels: bug

#5364 Signed-off-by: weijingchen <talkingwallace@sohu.com>
  python/fate/ml/nn/trainer/trainer_base.py
Labels: bug

#5365 Feature 2.0.0 rc sshe glm
  examples/pipeline/sshe_linr/test_linr_cv.py
  examples/pipeline/sshe_linr/test_linr_validate.py
  examples/pipeline/sshe_linr/test_linr_warm_start.py
  examples/pipeline/sshe_lr/test_lr_cv.py
  examples/pipeline/sshe_lr/test_lr_multi_class.py
  examples/pipeline/sshe_lr/test_lr_warm_start.py
  python/fate/ml/glm/hetero/sshe/sshe_linr.py
  python/fate/ml/glm/hetero/sshe/sshe_lr.py
Labels: enhancement, federatedml, examples

#5372 DataFrame Bug Fix When PSI Result Equals to 0
  python/fate/arch/dataframe/ops/_indexer.py
Labels: bug

#5377 Signed-off-by: weijingchen <talkingwallace@sohu.com> Remove logs
  python/fate/components/components/evaluation.py
Labels: bug

#5380 Signed-off-by: weijingchen <talkingwallace@sohu.com>
  examples/pipeline/hetero_secureboost/test_hetero_sbt_multi.py
  examples/pipeline/homo_nn/homo_nn_testsuite.yaml
  python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
Labels: bug, document

#5382 reqs: update version of transformers and accelerate
  python/requirements-fate.txt
Labels: document

#5391 add release note
  java/osx/RELEASE.md
Labels: document

#5394 edit release note
  RELEASE.md
Labels: document

#5400 example: update psi pipeline example
  examples/pipeline/psi/psi_testsuite.yaml
  examples/pipeline/psi/test_psi.py
  examples/pipeline/psi/test_psi_multi_host.py
Labels: examples

#5401 Dev 2.0.0 doc tutorial
  doc/2.0/fate/ml/hetero_nn_tutorial.md
  doc/2.0/fate/ml/hetero_secureboost_tutorial.ipynb
  doc/2.0/fate/ml/hetero_secureboost_tutorial.md
  doc/2.0/fate/ml/homo_nn_tutorial.ipynb
  doc/2.0/fate/ml/homo_nn_tutorial.md
  examples/benchmark_performance/hetero_secureboost/test_sbt.py
  examples/benchmark_quality/hetero_secureboost/pipeline_hetero_sbt.py
  examples/benchmark_quality/homo_nn/pipeline_nn_binary.py
  examples/benchmark_quality/homo_nn/pipeline_nn_multi.py
  examples/benchmark_quality/homo_nn/pipeline_nn_regression.py
  examples/pipeline/hetero_nn/hetero_nn_testsuite.yaml
  python/fate/components/components/homo_lr.py
  python/fate/ml/evaluation/classification.py
  python/fate/ml/nn/dataset/table.py
  python/fate/ml/nn/model_zoo/hetero_nn_model.py
Labels: federatedml, document

#5410 Feature 2.0.0 rc update doc
  RELEASE.md
  doc/2.0/fate/performance.md
Labels: document

#5416 doc update
  README.md
  README_zh.md
  doc/2.0/fate/components/linear_regression.md
  doc/2.0/fate/components/logistic_regression.md
  doc/2.0/fate/quick_start.md
Labels: document

#5412 Signed-off-by: weijingchen <talkingwallace@sohu.com>
  doc/tutorial/pipeline_tutorial_hetero.ipynb
  doc/tutorial/pipeline_tutorial_transform_local_file_to_dataframe.ipynb
  examples/pipeline/hetero_feature_selection/test_feature_selection_binning_lr.py
Labels: document

#5419 update doc of standalone deploy
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/README.zh.md
Labels: document

#5425 Dev 2.0.0 evaluation doc
  doc/2.0/fate/components/evaluation.md
Labels: document

#5427 update components readme
  doc/2.0/fate/components/README.md
  doc/2.0/fate/components/README.zh.md
  doc/2.0/fate/components/reader.md
Labels: document

#5428 Update Component Reader
  doc/2.0/fate/components/README.md
  doc/2.0/fate/components/README.zh.md
  doc/2.0/fate/components/evaluation.md
  doc/2.0/fate/components/reader.md
Labels: document

#5433 edit doc: update performance data of hetero_nn
  RELEASE.md
  doc/2.0/fate/performance.md
Labels: document
