Repository FederatedAI/FATE, pull requests merged in 2023-08, with the labels that each got.

#5026 dataframe: fix loc
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_indexer.py
Labels: bug

#5027 dataloader: ensure order
  python/fate/arch/dataframe/utils/_dataloader.py
  python/fate/ml/intersection/raw_intersection.py
Labels: arch

#5028 dataframe: fix vstack column retrieval problem
  python/fate/arch/dataframe/ops/_dimension_scaling.py
Labels: bug

#5030 add init param option & clean code(#4659)
  python/fate/components/components/coordinated_linr.py
  python/fate/components/components/coordinated_lr.py
  python/fate/components/core/params/_init_param.py
  python/fate/ml/glm/hetero/coordinated_linr/guest.py
  python/fate/ml/glm/hetero/coordinated_linr/host.py
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
  python/fate/ml/utils/_model_param.py
  python/fate/ml/utils/_optimizer.py
Labels: enhancement, federatedml

#5031 Feature 2.0.0 beta dataframe update
  python/fate/arch/dataframe/manager/block_manager.py
Labels: bug

#5036 Feature 2.0.0 beta round3 dataframe update
  python/fate/arch/dataframe/ops/_indexer.py
Labels: bug

#5039 Feature 2.0.0 beta dataframe refact
  python/fate/arch/dataframe/_frame_reader.py
  python/fate/arch/dataframe/conf/__init__.py
  python/fate/arch/dataframe/conf/default_config.py
  python/fate/arch/dataframe/manager/data_manager.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/arch/dataframe/ops/_indexer.py
  python/fate/arch/dataframe/ops/_where.py
  python/fate/arch/dataframe/utils/_sample.py
Labels: bug, arch

#5041 dataframe: fix as_tensor, optimizer psi
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/_frame_reader.py
  python/fate/arch/dataframe/ops/_indexer.py
  python/fate/arch/dataframe/ops/_transformer.py
  python/fate/arch/protocol/psi/ecdh/_run.py
Labels: bug, arch

#5043 Add Hetero Secureboost:
  python/fate/components/components/__init__.py
  python/fate/components/components/hetero_sbt.py
  python/fate/components/components/homo_nn.py
  python/fate/ml/ensemble/__init__.py
  python/fate/ml/ensemble/algo/secureboost/common/predict.py
  python/fate/ml/ensemble/algo/secureboost/hetero/_base.py
  python/fate/ml/ensemble/algo/secureboost/hetero/guest.py
  python/fate/ml/ensemble/algo/secureboost/hetero/host.py
  python/fate/ml/ensemble/algo/secureboost/test/test_hetero_sbt_binary.py
  python/fate/ml/ensemble/algo/secureboost/test/test_hetero_sbt_regression.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
  python/fate/ml/ensemble/learner/decision_tree/test/test_decision_tree.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/loss.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/splitter.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/subsample.py
  python/fate/ml/ensemble/utils/binning.py
  python/fate/ml/glm/hetero/coordinated_linr/host.py
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
  python/fate/ml/glm/hetero/coordinated_lr/host.py
  python/fate/test/test_histogram.py
Labels: federatedml

#5044 dataframe: optimizer indexer for psi
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/ops/_indexer.py
Labels: bug, arch

#5045 psi: speed up
  python/fate/arch/protocol/psi/ecdh/_run.py
Labels: arch

#5047 dataframe: fix loc_with_sample_id_replacement
  python/fate/arch/dataframe/ops/_indexer.py
Labels: bug

#5049 Fix bug in hetero-sbt:
  python/fate/components/components/hetero_sbt.py
  python/fate/ml/ensemble/algo/secureboost/hetero/guest.py
  python/fate/ml/ensemble/algo/secureboost/test/test_hetero_sbt_multi.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/loss.py
  python/fate/ml/evaluation/classification.py
Labels: bug, federatedml

#5051 dataframe: op optimize
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/ops/_apply_row.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/arch/dataframe/ops/_encoder.py
  python/fate/arch/dataframe/ops/_field_extract.py
  python/fate/arch/dataframe/ops/_indexer.py
  python/fate/arch/protocol/psi/ecdh/_run.py
Labels: arch

#5052 allow only default axis 0 for union(#4668)
  doc/2.0/README.md
  doc/2.0/components/README.md
  doc/2.0/components/data_split.md
  doc/2.0/components/feature_binning.md
  doc/2.0/components/feature_scale.md
  doc/2.0/components/feature_selection.md
  doc/2.0/components/linear_regression.md
  doc/2.0/components/logistic_regression.md
  doc/2.0/components/sample.md
  doc/2.0/components/statistics.md
  doc/2.0/components/union.md
  doc/2.0/images/HeteroLR.png
  doc/2.0/images/HeteroLinR.png
  doc/2.0/images/binning_principle.png
  doc/2.0/images/hetero_lr_multi_host.png
  doc/2.0/images/multi_host_selection.png
  doc/2.0/images/multiple_host_binning.png
  examples/benchmark_quality/lr/default_credit_config.yaml
  python/fate/components/components/union.py
  python/fate/ml/preprocessing/union.py
Labels: federatedml

#5054 dataframe: optimize op, modify histogram stat logic
  python/fate/arch/dataframe/ops/_apply_row.py
  python/fate/arch/dataframe/ops/_compress_block.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/arch/dataframe/ops/_histogram.py
  python/fate/arch/dataframe/ops/_indexer.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
Labels: arch

#5064 dataframe: update block compress logic
  python/fate/arch/dataframe/conf/default_config.py
  python/fate/arch/dataframe/ops/_compress_block.py
  python/fate/arch/dataframe/ops/_histogram.py
Labels: arch

#5072 Feature 2.0.0 beta dataframe refact
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/ops/_apply_row.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/arch/dataframe/ops/_indexer.py
  python/fate/arch/dataframe/ops/_set_item.py
Labels: arch

#5063 Feature 1.13 llm update
  python/fate_client/pipeline/component/homo_nn.py
  python/fate_client/pipeline/component/nn/backend/torch/cust.py
  python/federatedml/framework/homo/aggregator/aggregator_base.py
  python/federatedml/framework/homo/aggregator/secure_aggregator.py
  python/federatedml/framework/homo/blocks.py
  python/federatedml/nn/backend/torch/cust_model.py
  python/federatedml/nn/homo/_init.py
  python/federatedml/nn/homo/client.py
  python/federatedml/nn/homo/server.py
  python/federatedml/nn/homo/trainer/fedavg_trainer.py
  python/federatedml/nn/homo/trainer/trainer_base.py
  python/federatedml/param/homo_nn_param.py
Labels: federatedml

#5076 dataframe: fix set_item
  python/fate/arch/dataframe/ops/_set_item.py
Labels: bug

#5057 include performance suites for data generate(#5008)
  doc/tutorial/pipeline_tutorial_hetero.ipynb
  doc/tutorial/pipeline_tutorial_transform_local_file_to_dataframe.ipynb
  examples/pipeline/coordinated_lr/coordinated_lr_testsuite.yaml
  python/fate/components/components/coordinated_linr.py
  python/fate/components/components/coordinated_lr.py
  python/fate/ml/glm/hetero/coordinated_linr/host.py
  python/fate_test/fate_test/scripts/_utils.py
  python/fate_test/fate_test/scripts/generate_mock_data.py
  python/fate_test/pyproject.toml
  python/fate_test/setup.py
  python/requirements-fate-test.txt
Labels: enhancement

#5085 predict utils rename label name in predict result dataframe(#4659)
  examples/benchmark_performance/coordinated_lr/test_lr_sid.py
  examples/benchmark_quality/linr/fate-linr.py
  examples/benchmark_quality/lr/pipeline-lr-binary.py
  examples/benchmark_quality/lr/pipeline-lr-multi.py
  examples/pipeline/coordinated_linr/test_linr.py
  examples/pipeline/coordinated_linr/test_linr_multi_host.py
  examples/pipeline/coordinated_linr/test_linr_warm_start.py
  examples/pipeline/coordinated_lr/test_lr.py
  examples/pipeline/coordinated_lr/test_lr_multi_class.py
  examples/pipeline/coordinated_lr/test_lr_multi_host.py
  examples/pipeline/coordinated_lr/test_lr_validate.py
  examples/pipeline/coordinated_lr/test_lr_warm_start.py
  examples/pipeline/feature_scale/test_scale_w_lr.py
  examples/pipeline/multi_model/test_multi.py
  examples/pipeline/multi_model/test_multi_w_predict.py
  python/fate/ml/utils/predict_tools.py
Labels: federatedml, examples

#5089 predict tools add check for null label name
  python/fate/ml/utils/predict_tools.py
Labels: federatedml

#5091 Dev 2.0.0 gh
  python/fate/arch/context/_cipher.py
  python/fate/arch/histogram/histogram.py
  python/fate/ml/ensemble/algo/secureboost/test/test_hetero_sbt_binary.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
Labels: enhancement, federatedml

#5094 secureboost: remove duplicate operations
  python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
Labels: federatedml

#5096 secureboost: optimize dataframe op call
  python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
Labels: federatedml

#5099 dataframe: fix dataloader loc, vstack cat of pd.Index
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/ops/_indexer.py
  python/fate/arch/dataframe/utils/_dataloader.py
  python/fate/arch/dataframe/utils/_sample.py
Labels: bug

#5102 edit configuration in pipeline tutorial
  doc/tutorial/pipeline_tutorial_hetero.ipynb
Labels: federatedml, document

#5104 dataframe & secureboost optimize
  python/fate/arch/dataframe/_dataframe.py
  python/fate/arch/dataframe/manager/block_manager.py
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/arch/dataframe/ops/_indexer.py
  python/fate/arch/dataframe/utils/_k_fold.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
Labels: arch, federatedml

#5103 Feature 1.11.3 nn update
  python/federatedml/framework/homo/aggregator/secure_aggregator.py
  python/federatedml/framework/homo/blocks.py
  python/federatedml/nn/homo/_init.py
  python/federatedml/nn/homo/trainer/fedavg_trainer.py
  python/federatedml/nn/homo/trainer/trainer_base.py
Labels: federatedml

#5106 Feature 2.0.0 beta dataframe refact
  python/fate/arch/histogram/histogram.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
  python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
  python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
Labels: arch, federatedml

#5108 dataframe: fix bug of loc datamanager inplace
  python/fate/arch/dataframe/ops/_dimension_scaling.py
  python/fate/arch/dataframe/ops/_indexer.py
Labels: bug
