Repository FederatedAI/FATE, pull requests merged in 2024-03, with the labels that each got.

#5517 update performance doc
  doc/2.0/fate/performance/peformance_comparision.md
  doc/2.0/fate/performance/performance_multi_engines.md
Labels: document

#5518 fix performance doc
  doc/2.0/fate/performance/performance_comparison.md
  doc/2.0/fate/performance/performance_multi_engines.md
Labels: document

#5528 Fix agg type in component Signed-off-by: weijingchen <talkingwallace@…
  python/fate/components/components/nn/runner/homo_default_runner.py
Labels: bug

#5529 rename examples pipeline doc
  examples/pipeline/coordinated_linr/README.md
  examples/pipeline/coordinated_lr/README.md
  examples/pipeline/data_split/README.md
  examples/pipeline/feature_correlation/README.md
  examples/pipeline/feature_scale/README.md
  examples/pipeline/hetero_feature_binning/README.md
  examples/pipeline/hetero_feature_selection/README.md
  examples/pipeline/hetero_nn/README.md
  examples/pipeline/hetero_secureboost/README.md
  examples/pipeline/homo_lr/README.md
  examples/pipeline/homo_nn/README.md
  examples/pipeline/multi_model/README.md
  examples/pipeline/psi/README.md
  examples/pipeline/sample/README.md
  examples/pipeline/sshe_linr/README.md
  examples/pipeline/sshe_lr/README.md
  examples/pipeline/statistics/README.md
  examples/pipeline/union/README.md
  examples/pipeline/upload/README.md
Labels: document

#5527 update readme of doc
  doc/2.0/fate/quick_start.md
  doc/README.md
  doc/tutorial/pipeline_tutorial_hetero.ipynb
Labels: document

#5533 update bq Signed-off-by: weijingchen <talkingwallace@sohu.com>
  examples/benchmark_quality/hetero_nn/hetero_nn.py
  examples/benchmark_quality/hetero_secureboost/pipeline_hetero_sbt.py
  examples/benchmark_quality/homo_nn/pipeline_nn_binary.py
  examples/benchmark_quality/homo_nn/pipeline_nn_multi.py
  examples/benchmark_quality/homo_nn/pipeline_nn_regression.py
  examples/benchmark_quality/linr/fate-linr.py
  examples/benchmark_quality/linr/fate-sshe-linr.py
  examples/benchmark_quality/lr/pipeline-lr-binary.py
  examples/benchmark_quality/lr/pipeline-lr-multi.py
  examples/benchmark_quality/lr/pipeline-sshe-lr-binary.py
  examples/benchmark_quality/lr/pipeline-sshe-lr-multi.py
Labels: bug, document

#5535 benchmark config adopt newer param format for sklearn
  examples/benchmark_quality/linr/linr_sklearn_config.yaml
  examples/benchmark_quality/lr/breast_lr_sklearn_config.yaml
  examples/benchmark_quality/lr/default_credit_lr_sklearn_config.yaml
  examples/benchmark_quality/lr/epsilon_5k_lr_sklearn_config.yaml
  examples/benchmark_quality/lr/give_credit_lr_sklearn_config.yaml
  examples/benchmark_quality/lr/sklearn-lr-binary.py
  examples/benchmark_quality/lr/sklearn-lr-multi.py
  examples/benchmark_quality/lr/vehicle_lr_sklearn_config.yaml
Labels: enhancement, document, examples
