Repository FederatedAI/FATE, pull requests merged in 2024-06, with the labels that each got.

#5639 aggregator: support bfloat16 dtype agg
  python/fate/ml/aggregator/base.py
Labels: enhancement

#5640 Add arbiter features Signed-off-by: weijingchen <talkingwallace@sohu.…
  python/fate/components/components/homo_nn.py
Labels: federatedml

#5626 update quick start
  doc/2.0/fate/quick_start.md
Labels: document

#5633 add homo quick start
  README.md
  doc/2.0/fate/homo_quick_start.md
  doc/README.md
Labels: document

#5643 fix doc link
  doc/README.md
Labels: document

#5644 Fix hetero-nn doc
  doc/2.0/fate/components/hetero_nn.md
Labels: document

#5646 update gitmodule file
  .gitmodules
Labels: document
