Repository FederatedAI/FATE, pull requests merged in 2024-02, with the labels that each got.

#5483 update req
  python/requirements.txt
Labels: document, deploy

#5484 regenerate pb
  python/fate_client/pyproject.toml
  python/fate_client/setup.py
  python/fate_test/pyproject.toml
  python/fate_test/setup.py
  python/federatedml/protobuf/generated/boosting_tree_model_meta_pb2.py
  python/federatedml/protobuf/generated/boosting_tree_model_param_pb2.py
  python/federatedml/protobuf/generated/column_expand_meta_pb2.py
  python/federatedml/protobuf/generated/column_expand_param_pb2.py
  python/federatedml/protobuf/generated/data_io_meta_pb2.py
  python/federatedml/protobuf/generated/data_io_param_pb2.py
  python/federatedml/protobuf/generated/data_transform_meta_pb2.py
  python/federatedml/protobuf/generated/data_transform_param_pb2.py
  python/federatedml/protobuf/generated/feature_binning_meta_pb2.py
  python/federatedml/protobuf/generated/feature_binning_param_pb2.py
  python/federatedml/protobuf/generated/feature_imputation_meta_pb2.py
  python/federatedml/protobuf/generated/feature_imputation_param_pb2.py
  python/federatedml/protobuf/generated/feature_scale_meta_pb2.py
  python/federatedml/protobuf/generated/feature_scale_param_pb2.py
  python/federatedml/protobuf/generated/feature_selection_meta_pb2.py
  python/federatedml/protobuf/generated/feature_selection_param_pb2.py
  python/federatedml/protobuf/generated/ftl_model_meta_pb2.py
  python/federatedml/protobuf/generated/ftl_model_param_pb2.py
  python/federatedml/protobuf/generated/hetero_kmeans_meta_pb2.py
  python/federatedml/protobuf/generated/hetero_kmeans_param_pb2.py
  python/federatedml/protobuf/generated/hetero_nn_model_meta_pb2.py
  python/federatedml/protobuf/generated/hetero_nn_model_param_pb2.py
  python/federatedml/protobuf/generated/homo_nn_model_meta_pb2.py
  python/federatedml/protobuf/generated/homo_nn_model_param_pb2.py
  python/federatedml/protobuf/generated/label_transform_meta_pb2.py
  python/federatedml/protobuf/generated/label_transform_param_pb2.py
  python/federatedml/protobuf/generated/linr_model_meta_pb2.py
  python/federatedml/protobuf/generated/linr_model_param_pb2.py
  python/federatedml/protobuf/generated/lr_model_meta_pb2.py
  python/federatedml/protobuf/generated/lr_model_param_pb2.py
  python/federatedml/protobuf/generated/one_vs_rest_param_pb2.py
  python/federatedml/protobuf/generated/onehot_meta_pb2.py
  python/federatedml/protobuf/generated/onehot_param_pb2.py
  python/federatedml/protobuf/generated/pearson_model_meta_pb2.py
  python/federatedml/protobuf/generated/pearson_model_param_pb2.py
  python/federatedml/protobuf/generated/pipeline_pb2.py
  python/federatedml/protobuf/generated/poisson_model_meta_pb2.py
  python/federatedml/protobuf/generated/poisson_model_param_pb2.py
  python/federatedml/protobuf/generated/psi_model_meta_pb2.py
  python/federatedml/protobuf/generated/psi_model_param_pb2.py
  python/federatedml/protobuf/generated/sample_weight_model_meta_pb2.py
  python/federatedml/protobuf/generated/sample_weight_model_param_pb2.py
  python/federatedml/protobuf/generated/sir_meta_pb2.py
  python/federatedml/protobuf/generated/sir_param_pb2.py
  python/federatedml/protobuf/generated/sshe_cipher_param_pb2.py
  python/federatedml/protobuf/generated/statistic_meta_pb2.py
  python/federatedml/protobuf/generated/statistic_param_pb2.py
  python/requirements.txt
Labels: dependencies

#5499 Feature 2.0.0 fix dataframe join order
  python/fate/arch/dataframe/ops/_dimension_scaling.py
Labels: bug

#5505 add build os to readthedocs
  .readthedocs.yml
Labels: document

#5488 Feature 2.0.0 doc patch
  doc/2.0/fate/components/README.md
  doc/2.0/fate/components/README.zh.md
  doc/develop_guide/component_guide.md
  examples/pipeline/coordinated_linr/coordinated_linr.md
  examples/pipeline/coordinated_lr/coordinated_lr.md
  examples/pipeline/data_split/data_split.md
  examples/pipeline/feature_correlation/feature_correlation.md
  examples/pipeline/feature_scale/feature_scale.md
  examples/pipeline/hetero_feature_binning/hetero_feature_binning.md
  examples/pipeline/hetero_feature_selection/hetero_feature_selection.md
  examples/pipeline/hetero_nn/hetero_nn.md
  examples/pipeline/hetero_secureboost/hetero_secureboost.md
  examples/pipeline/homo_lr/homo_lr.md
  examples/pipeline/homo_nn/homo_nn.md
  examples/pipeline/multi_model/multi_model.md
  examples/pipeline/psi/psi.md
  examples/pipeline/sample/sample.md
  examples/pipeline/sshe_linr/sshe_linr.md
  examples/pipeline/sshe_lr/sshe_lr.md
  examples/pipeline/statistics/statistics.md
  examples/pipeline/union/union.md
  examples/pipeline/upload/upload.md
  python/fate/ml/glm/hetero/coordinated_lr/guest.py
Labels: document

#5509 Update evaluation input
  examples/pipeline/coordinated_linr/test_linr.py
  examples/pipeline/coordinated_linr/test_linr_multi_host.py
  examples/pipeline/coordinated_linr/test_linr_warm_start.py
  examples/pipeline/coordinated_lr/test_lr.py
  examples/pipeline/coordinated_lr/test_lr_multi_class.py
  examples/pipeline/coordinated_lr/test_lr_multi_host.py
  examples/pipeline/coordinated_lr/test_lr_predict_w_torch.py
  examples/pipeline/coordinated_lr/test_lr_validate.py
  examples/pipeline/coordinated_lr/test_lr_warm_start.py
  examples/pipeline/feature_scale/test_scale_w_lr.py
  examples/pipeline/hetero_nn/test_nn_binary_fedpass.py
  examples/pipeline/hetero_nn/test_nn_binary_sshe.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_binary_warm_start.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_multi.py
  examples/pipeline/hetero_secureboost/test_hetero_sbt_regression.py
  examples/pipeline/homo_lr/test_homo_lr_binary.py
  examples/pipeline/homo_lr/test_homo_lr_multi_ovr.py
  examples/pipeline/homo_nn/test_nn_binary.py
  examples/pipeline/homo_nn/test_nn_multi.py
  examples/pipeline/homo_nn/test_nn_regression.py
  examples/pipeline/sshe_linr/test_linr.py
  examples/pipeline/sshe_linr/test_linr_validate.py
  examples/pipeline/sshe_linr/test_linr_warm_start.py
  examples/pipeline/sshe_lr/test_lr.py
  examples/pipeline/sshe_lr/test_lr_multi_class.py
  examples/pipeline/sshe_lr/test_lr_predict_w_torch.py
  examples/pipeline/sshe_lr/test_lr_validate.py
  examples/pipeline/sshe_lr/test_lr_warm_start.py
  python/fate/components/components/evaluation.py
Labels: examples

#5511 update version of fate from 2.0.0 to 2.1.0
  deploy/standalone-deploy/README.md
  deploy/standalone-deploy/README.zh.md
  doc/2.0/fate/quick_start.md
  python/fate/_info.py
Labels: document
